AMBIL DATA 2018-2022

In [47]:
import pandas as pd

# 1. Baca dataset
df = pd.read_csv('jumlah_tenaga_kesehatan.csv')

# 2. cek periode_update STRING
df['periode_update'] = df['periode_update'].astype(str)

# 3. Ambil tahun
df['tahun'] = df['periode_update'].str[:4]

# 4. Jumlahkan seluruh kategori penyakit per tahun per kabupaten
df_tahun_kab_2018 = (
    df.groupby([
        'kode_kabupaten_kota',
        'nama_kabupaten_kota',
        'tahun'
    ])['jumlah']
    .sum()
    .reset_index()
)
df_tahun_kab_2018 = df_tahun_kab_2018.rename(columns={
    'jumlah': 'JUMLAH_TENAGA_KESEHATAN'
})

# 5. Urutkan berdasarkan tahun ASC dan nama kabupaten-kota ASC
df_tahun_kab_2018 = df_tahun_kab_2018.sort_values(
    ['tahun', 'kode_kabupaten_kota'],
    ascending=[True, True]
).reset_index(drop=True)

df_tahun_kab_2018

     kode_kabupaten_kota    nama_kabupaten_kota tahun  JUMLAH_TENAGA_KESEHATAN
0                   3501      KABUPATEN PACITAN  2018                     1441
1                   3502     KABUPATEN PONOROGO  2018                     2086
2                   3503   KABUPATEN TRENGGALEK  2018                     1827
3                   3504  KABUPATEN TULUNGAGUNG  2018                     2520
4                   3505       KABUPATEN BLITAR  2018                     2051
..                   ...                    ...   ...                      ...
185                 3575          KOTA PASURUAN  2022                     1180
186                 3576         KOTA MOJOKERTO  2022                     2077
187                 3577            KOTA MADIUN  2022                     3075
188                 3578          KOTA SURABAYA  2022                    29873
189                 3579              KOTA BATU  2022                     1340

[190 rows x 4 columns]

In [48]:
df_tahun_kab_2018.shape

(190, 4)

AMBIL DATA 2023-2024

In [49]:
import pandas as pd

df = pd.read_csv('jmlh_tng_kshtn_mnrt_kbptn_kt_cl.csv')

# 1. Tahun string
df['tahun'] = df['tahun'].astype(str)

# 2. Ambil tahun 2023 & 2024
df = df[df['tahun'].isin(['2023', '2024'])]

# 3. Hapus baris provinsi
df = df[
    ~df['kabupatenkota']
      .str.strip()
      .str.upper()
      .eq('JAWA TIMUR')
]

# 4. Jumlahkan per kabupaten per tahun
df_tahun_kab_2023 = (
    df.groupby(
        ['kabupatenkota', 'tahun']
    )['jumlah']
    .sum()
    .reset_index()
)

# 5. Rename kolom
df_tahun_kab_2023 = df_tahun_kab_2023.rename(columns={
    'kabupatenkota': 'nama_kabupaten_kota',
    'jumlah': 'JUMLAH_TENAGA_KESEHATAN'
})

# 6. Sort
df_tahun_kab_2023 = df_tahun_kab_2023.sort_values(
    ['tahun', 'nama_kabupaten_kota'],
    ascending=[True, True]
).reset_index(drop=True)

df_tahun_kab_2023['JUMLAH_TENAGA_KESEHATAN'] = (
    df_tahun_kab_2023['JUMLAH_TENAGA_KESEHATAN']
    .round()
    .astype('Int64')
)

# 7. Tampilkan hasil
df_tahun_kab_2023

     nama_kabupaten_kota tahun  JUMLAH_TENAGA_KESEHATAN
0    Kabupaten Bangkalan  2023                     2504
1   Kabupaten Banyuwangi  2023                     3659
2       Kabupaten Blitar  2023                     2339
3   Kabupaten Bojonegoro  2023                     3351
4    Kabupaten Bondowoso  2023                     2170
..                   ...   ...                      ...
71           Kota Malang  2024                     9377
72        Kota Mojokerto  2024                     2191
73         Kota Pasuruan  2024                     1480
74      Kota Probolinggo  2024                     1580
75         Kota Surabaya  2024                    29797

[76 rows x 3 columns]

In [50]:
df_tahun_kab_2023.shape

(76, 3)

ISI KODE KABUPATEN KOTA

In [51]:
import pandas as pd

# =====================================================
# DATA MASTER KODE WILAYAH 
# =====================================================

df_master = pd.read_csv('jumlah_tenaga_kesehatan.csv')

# rapikan nama kolom
df_master.columns = df_master.columns.str.strip()

# standarisasi nama kabupaten
df_master['nama_kabupaten_kota'] = (
    df_master['nama_kabupaten_kota']
    .astype(str)
    .str.strip()
    .str.upper()
)

# ambil mapping
master_kabkot = (
    df_master[['kode_kabupaten_kota', 'nama_kabupaten_kota']]
    .drop_duplicates()
)

master_kabkot

     kode_kabupaten_kota    nama_kabupaten_kota
0                   3501      KABUPATEN PACITAN
15                  3502     KABUPATEN PONOROGO
30                  3503   KABUPATEN TRENGGALEK
45                  3504  KABUPATEN TULUNGAGUNG
60                  3505       KABUPATEN BLITAR
75                  3506       KABUPATEN KEDIRI
90                  3507       KABUPATEN MALANG
105                 3508     KABUPATEN LUMAJANG
120                 3509       KABUPATEN JEMBER
135                 3510   KABUPATEN BANYUWANGI
150                 3511    KABUPATEN BONDOWOSO
165                 3512    KABUPATEN SITUBONDO
180                 3513  KABUPATEN PROBOLINGGO
195                 3514     KABUPATEN PASURUAN
210                 3515     KABUPATEN SIDOARJO
225                 3516    KABUPATEN MOJOKERTO
240                 3517      KABUPATEN JOMBANG
255                 3518      KABUPATEN NGANJUK
270                 3519       KABUPATEN MADIUN
285                 3520      KABUPATEN MAGETAN
300                 3521        KABUPATEN NGAWI
315                 3522   KABUPATEN BOJONEGORO
330                 3523        KABUPATEN TUBAN
345                 3524     KABUPATEN LAMONGAN
360                 3525       KABUPATEN GRESIK
375                 3526    KABUPATEN BANGKALAN
390                 3527      KABUPATEN SAMPANG
405                 3528    KABUPATEN PAMEKASAN
420                 3529      KABUPATEN SUMENEP
435                 3571            KOTA KEDIRI
450                 3572            KOTA BLITAR
465                 3573            KOTA MALANG
480                 3574       KOTA PROBOLINGGO
495                 3575          KOTA PASURUAN
510                 3576         KOTA MOJOKERTO
525                 3577            KOTA MADIUN
540                 3578          KOTA SURABAYA
555                 3579              KOTA BATU

In [52]:
# =====================================================
# DATA TENAGA KESEHATAN (2023–2024)
# =====================================================

df = pd.read_csv('jmlh_tng_kshtn_mnrt_kbptn_kt_cl.csv')

# rapikan nama kolom
df.columns = df.columns.str.strip()

# tahun string
df['tahun'] = df['tahun'].astype(str)

# filter tahun
df = df[df['tahun'].isin(['2023', '2024'])]

# hapus agregat provinsi
df = df[
    ~df['kabupatenkota']
      .astype(str)
      .str.strip()
      .str.upper()
      .eq('JAWA TIMUR')
]

# standarisasi nama kabupaten
df['nama_kabupaten_kota'] = (
    df['kabupatenkota']
    .astype(str)
    .str.strip()
    .str.upper()
)

# =====================================================
# AGREGASI PER KABUPATEN PER TAHUN
# =====================================================

df_tahun_kab_2023 = (
    df.groupby(
        ['nama_kabupaten_kota', 'tahun']
    )['jumlah']
    .sum()
    .reset_index()
)

df_tahun_kab_2023 = df_tahun_kab_2023.rename(columns={
    'jumlah': 'JUMLAH_TENAGA_KESEHATAN'
})

# =====================================================
# MERGE KODE KABUPATEN 
# =====================================================

# pastikan data TIDAK punya kolom kode
df_tahun_kab_2023 = df_tahun_kab_2023.drop(
    columns=['kode_kabupaten_kota'],
    errors='ignore'
)

# merge
df_tahun_kab_2023 = df_tahun_kab_2023.merge(
    master_kabkot,
    on='nama_kabupaten_kota',
    how='left'
)

# =====================================================
# FORMAT AKHIR
# =====================================================

df_tahun_kab_2023 = df_tahun_kab_2023.sort_values(
    ['tahun', 'kode_kabupaten_kota']
).reset_index(drop=True)

# kembalikan format penulisan
df_tahun_kab_2023['nama_kabupaten_kota'] = (
    df_tahun_kab_2023['nama_kabupaten_kota']
    .str.title()
)
df_tahun_kab_2023 = df_tahun_kab_2023[
    [
        'kode_kabupaten_kota',
        'nama_kabupaten_kota',
        'tahun',
        'JUMLAH_TENAGA_KESEHATAN'
    ]
]

df_tahun_kab_2023['JUMLAH_TENAGA_KESEHATAN'] = (
    df_tahun_kab_2023['JUMLAH_TENAGA_KESEHATAN']
    .round()
    .astype('Int64')  )

df_tahun_kab_2023

    kode_kabupaten_kota    nama_kabupaten_kota tahun  JUMLAH_TENAGA_KESEHATAN
0                  3501      Kabupaten Pacitan  2023                     1366
1                  3502     Kabupaten Ponorogo  2023                     2819
2                  3503   Kabupaten Trenggalek  2023                     1789
3                  3504  Kabupaten Tulungagung  2023                     3847
4                  3505       Kabupaten Blitar  2023                     2339
..                  ...                    ...   ...                      ...
71                 3575          Kota Pasuruan  2024                     1480
72                 3576         Kota Mojokerto  2024                     2191
73                 3577            Kota Madiun  2024                     3519
74                 3578          Kota Surabaya  2024                    29797
75                 3579              Kota Batu  2024                     1527

[76 rows x 4 columns]

In [53]:
# =====================================================
# GABUNG DATA 
# =====================================================

df_nakes = pd.concat(
    [
        df_tahun_kab_2018,
        df_tahun_kab_2023
    ],
    axis=0,
    ignore_index=True
)

# urutkan
df_nakes = df_nakes.sort_values(
    ['tahun', 'kode_kabupaten_kota']
).reset_index(drop=True)

df_nakes

     kode_kabupaten_kota    nama_kabupaten_kota tahun  JUMLAH_TENAGA_KESEHATAN
0                   3501      KABUPATEN PACITAN  2018                     1441
1                   3502     KABUPATEN PONOROGO  2018                     2086
2                   3503   KABUPATEN TRENGGALEK  2018                     1827
3                   3504  KABUPATEN TULUNGAGUNG  2018                     2520
4                   3505       KABUPATEN BLITAR  2018                     2051
..                   ...                    ...   ...                      ...
261                 3575          Kota Pasuruan  2024                     1480
262                 3576         Kota Mojokerto  2024                     2191
263                 3577            Kota Madiun  2024                     3519
264                 3578          Kota Surabaya  2024                    29797
265                 3579              Kota Batu  2024                     1527

[266 rows x 4 columns]

In [54]:
df_nakes.shape

(266, 4)

SIMPAN DATA CSV

In [55]:
df_nakes.to_csv('data_tenagakesehatan.csv', index=False)