AMBIL DATA 2018

In [32]:
import pandas as pd

# 1. Baca data
df = pd.read_csv(
    "Jumlah Penduduk Menurut Jenis Kelamin dan Kabupaten_Kota Provinsi Jawa Timur, 2018.csv"
)

# 2. Rename kolom (karena header-nya berantakan)
df.columns = [
    'nama_kabupaten_kota',
    'laki_laki',
    'perempuan',
    'total_existing'
]

# 3. Buang baris header tambahan
df = df.iloc[3:].reset_index(drop=True)

# 4. Ubah ke numerik
df['laki_laki'] = pd.to_numeric(df['laki_laki'], errors='coerce')
df['perempuan'] = pd.to_numeric(df['perempuan'], errors='coerce')

# 5. Hitung jumlah penduduk
df['jumlah_penduduk'] = df['laki_laki'] + df['perempuan']

# 6. Ambil kolom final
df_penduduk_2018 = df[['nama_kabupaten_kota', 'jumlah_penduduk']]

df_penduduk_2018 = df_penduduk_2018[
    df_penduduk_2018['nama_kabupaten_kota'].str.strip().str.lower() != 'jawa timur'
]

# Tambahkan kolom tahun
df_penduduk_2018['tahun'] = 2018

df_penduduk_2018 = df_penduduk_2018[
    ['nama_kabupaten_kota', 'tahun', 'jumlah_penduduk']
]

df_penduduk_2018

      nama_kabupaten_kota  tahun  jumlah_penduduk
0       Kabupaten Pacitan   2018           554394
1      Kabupaten Ponorogo   2018           870705
2    Kabupaten Trenggalek   2018           694902
3   Kabupaten Tulungagung   2018          1035290
4        Kabupaten Blitar   2018          1157500
5        Kabupaten Kediri   2018          1568113
6        Kabupaten Malang   2018          2591795
7      Kabupaten Lumajang   2018          1039794
8        Kabupaten Jember   2018          2440714
9    Kabupaten Banyuwangi   2018          1609677
10    Kabupaten Bondowoso   2018           772297
11    Kabupaten Situbondo   2018           679993
12  Kabupaten Probolinggo   2018          1162092
13     Kabupaten Pasuruan   2018          1616578
14     Kabupaten Sidoarjo   2018          2216804
15    Kabupaten Mojokerto   2018          1108718
16      Kabupaten Jombang   2018          1258618
17      Kabupaten Nganjuk   2018          1051900
18       Kabupaten Madiun   2018           681394
19      Kabupaten Magetan   2018           628924
20        Kabupaten Ngawi   2018           830090
21   Kabupaten Bojonegoro   2018          1246927
22        Kabupaten Tuban   2018          1168277
23     Kabupaten Lamongan   2018          1188913
24       Kabupaten Gresik   2018          1299024
25    Kabupaten Bangkalan   2018           978892
26      Kabupaten Sampang   2018           968520
27    Kabupaten Pamekasan   2018           871497
28      Kabupaten Sumenep   2018          1085227
29            Kota Kediri   2018           285582
30            Kota Blitar   2018           140971
31            Kota Malang   2018           866118
32       Kota Probolinggo   2018           235211
33          Kota Pasuruan   2018           199078
34         Kota Mojokerto   2018           128282
35            Kota Madiun   2018           176697
36          Kota Surabaya   2018          2885555
37              Kota Batu   2018           205788

AMBIL DATA 2019

In [33]:
import pandas as pd

# 1. Baca data
df = pd.read_csv(
    "Jumlah Penduduk Menurut Jenis Kelamin dan Kabupaten_Kota Provinsi Jawa Timur, 2019.csv"
)

# 2. Rename kolom (karena header-nya berantakan)
df.columns = [
    'nama_kabupaten_kota',
    'laki_laki',
    'perempuan',
    'total_existing'
]

# 3. Buang baris header tambahan
df = df.iloc[3:].reset_index(drop=True)

# 4. Ubah ke numerik
df['laki_laki'] = pd.to_numeric(df['laki_laki'], errors='coerce')
df['perempuan'] = pd.to_numeric(df['perempuan'], errors='coerce')

# 5. Hitung jumlah penduduk
df['jumlah_penduduk'] = df['laki_laki'] + df['perempuan']

# 6. Ambil kolom final
df_penduduk_2019 = df[['nama_kabupaten_kota', 'jumlah_penduduk']]

df_penduduk_2019 = df_penduduk_2019[
    df_penduduk_2019['nama_kabupaten_kota'].str.strip().str.lower() != 'jawa timur'
]

# Tambahkan kolom tahun
df_penduduk_2019['tahun'] = 2019

df_penduduk_2019 = df_penduduk_2019[
    ['nama_kabupaten_kota', 'tahun', 'jumlah_penduduk']
]

df_penduduk_2019

      nama_kabupaten_kota  tahun  jumlah_penduduk
0       Kabupaten Pacitan   2019           555304
1      Kabupaten Ponorogo   2019           871370
2    Kabupaten Trenggalek   2019           696295
3   Kabupaten Tulungagung   2019          1039284
4        Kabupaten Blitar   2019          1160677
5        Kabupaten Kediri   2019          1574272
6        Kabupaten Malang   2019          2606204
7      Kabupaten Lumajang   2019          1042395
8        Kabupaten Jember   2019          2450668
9    Kabupaten Banyuwangi   2019          1613991
10    Kabupaten Bondowoso   2019           775715
11    Kabupaten Situbondo   2019           682978
12  Kabupaten Probolinggo   2019          1168503
13     Kabupaten Pasuruan   2019          1627396
14     Kabupaten Sidoarjo   2019          2249476
15    Kabupaten Mojokerto   2019          1117688
16      Kabupaten Jombang   2019          1263814
17      Kabupaten Nganjuk   2019          1054611
18       Kabupaten Madiun   2019           682684
19      Kabupaten Magetan   2019           628977
20        Kabupaten Ngawi   2019           830108
21   Kabupaten Bojonegoro   2019          1249692
22        Kabupaten Tuban   2019          1172790
23     Kabupaten Lamongan   2019          1189106
24       Kabupaten Gresik   2019          1312881
25    Kabupaten Bangkalan   2019           986672
26      Kabupaten Sampang   2019           978875
27    Kabupaten Pamekasan   2019           879992
28      Kabupaten Sumenep   2019          1088910
29            Kota Kediri   2019           287409
30            Kota Blitar   2019           141876
31            Kota Malang   2019           870682
32       Kota Probolinggo   2019           237208
33          Kota Pasuruan   2019           200422
34         Kota Mojokerto   2019           129014
35            Kota Madiun   2019           177007
36          Kota Surabaya   2019          2896195
37              Kota Batu   2019           207490

AMBIL DATA 2020

In [34]:
import pandas as pd

# 1. Baca data
df = pd.read_csv(
    "Jumlah Penduduk Menurut Jenis Kelamin dan Kabupaten_Kota Provinsi Jawa Timur, 2020.csv"
)

# 2. Rename kolom (karena header-nya berantakan)
df.columns = [
    'nama_kabupaten_kota',
    'laki_laki',
    'perempuan',
    'total_existing'
]

# 3. Buang baris header tambahan
df = df.iloc[3:].reset_index(drop=True)

# 4. Ubah ke numerik
df['laki_laki'] = pd.to_numeric(df['laki_laki'], errors='coerce')
df['perempuan'] = pd.to_numeric(df['perempuan'], errors='coerce')

# 5. Hitung jumlah penduduk
df['jumlah_penduduk'] = df['laki_laki'] + df['perempuan']

# 6. Ambil kolom final
df_penduduk_2020 = df[['nama_kabupaten_kota', 'jumlah_penduduk']]

df_penduduk_2020 = df_penduduk_2020[
    df_penduduk_2020['nama_kabupaten_kota'].str.strip().str.lower() != 'jawa timur'
]

# Tambahkan kolom tahun
df_penduduk_2020['tahun'] = 2020

df_penduduk_2020 = df_penduduk_2020[
    ['nama_kabupaten_kota', 'tahun', 'jumlah_penduduk']
]

df_penduduk_2020

      nama_kabupaten_kota  tahun  jumlah_penduduk
0       Kabupaten Pacitan   2020           586110
1      Kabupaten Ponorogo   2020           949318
2    Kabupaten Trenggalek   2020           731125
3   Kabupaten Tulungagung   2020          1089775
4        Kabupaten Blitar   2020          1223745
5        Kabupaten Kediri   2020          1635294
6        Kabupaten Malang   2020          2654448
7      Kabupaten Lumajang   2020          1119251
8        Kabupaten Jember   2020          2536729
9    Kabupaten Banyuwangi   2020          1708114
10    Kabupaten Bondowoso   2020           776151
11    Kabupaten Situbondo   2020           685967
12  Kabupaten Probolinggo   2020          1152537
13     Kabupaten Pasuruan   2020          1605969
14     Kabupaten Sidoarjo   2020          2082801
15    Kabupaten Mojokerto   2020          1119209
16      Kabupaten Jombang   2020          1318062
17      Kabupaten Nganjuk   2020          1103902
18       Kabupaten Madiun   2020           744350
19      Kabupaten Magetan   2020           670812
20        Kabupaten Ngawi   2020           870057
21   Kabupaten Bojonegoro   2020          1301635
22        Kabupaten Tuban   2020          1198012
23     Kabupaten Lamongan   2020          1344165
24       Kabupaten Gresik   2020          1311215
25    Kabupaten Bangkalan   2020          1060377
26      Kabupaten Sampang   2020           969694
27    Kabupaten Pamekasan   2020           850057
28      Kabupaten Sumenep   2020          1124436
29            Kota Kediri   2020           286796
30            Kota Blitar   2020           149149
31            Kota Malang   2020           843810
32       Kota Probolinggo   2020           239649
33          Kota Pasuruan   2020           208006
34         Kota Mojokerto   2020           132434
35            Kota Madiun   2020           195175
36          Kota Surabaya   2020          2874314
37              Kota Batu   2020           213046

AMBIL DATA 2021

In [35]:
import pandas as pd

# 1. Baca data
df = pd.read_csv(
    "Jumlah Penduduk Menurut Jenis Kelamin dan Kabupaten_Kota Provinsi Jawa Timur, 2021.csv"
)

# 2. Rename kolom (karena header-nya berantakan)
df.columns = [
    'nama_kabupaten_kota',
    'laki_laki',
    'perempuan',
    'total_existing'
]

# 3. Buang baris header tambahan
df = df.iloc[3:].reset_index(drop=True)

# 4. Ubah ke numerik
df['laki_laki'] = pd.to_numeric(df['laki_laki'], errors='coerce')
df['perempuan'] = pd.to_numeric(df['perempuan'], errors='coerce')

# 5. Hitung jumlah penduduk
df['jumlah_penduduk'] = df['laki_laki'] + df['perempuan']

# 6. Ambil kolom final
df_penduduk_2021 = df[['nama_kabupaten_kota', 'jumlah_penduduk']]

df_penduduk_2021 = df_penduduk_2021[
    df_penduduk_2021['nama_kabupaten_kota'].str.strip().str.lower() != 'jawa timur'
]

# Tambahkan kolom tahun
df_penduduk_2021['tahun'] = 2021

df_penduduk_2021 = df_penduduk_2021[
    ['nama_kabupaten_kota', 'tahun', 'jumlah_penduduk']
]

df_penduduk_2021

      nama_kabupaten_kota  tahun  jumlah_penduduk
0       Kabupaten Pacitan   2021           589108
1      Kabupaten Ponorogo   2021           955839
2    Kabupaten Trenggalek   2021           734888
3   Kabupaten Tulungagung   2021          1096588
4        Kabupaten Blitar   2021          1231013
5        Kabupaten Kediri   2021          1644400
6        Kabupaten Malang   2021          2668296
7      Kabupaten Lumajang   2021          1127094
8        Kabupaten Jember   2021          2550360
9    Kabupaten Banyuwangi   2021          1718462
10    Kabupaten Bondowoso   2021           778525
11    Kabupaten Situbondo   2021           688337
12  Kabupaten Probolinggo   2021          1155894
13     Kabupaten Pasuruan   2021          1611805
14     Kabupaten Sidoarjo   2021          2091930
15    Kabupaten Mojokerto   2021          1125522
16      Kabupaten Jombang   2021          1325914
17      Kabupaten Nganjuk   2021          1109683
18       Kabupaten Madiun   2021           750143
19      Kabupaten Magetan   2021           674133
20        Kabupaten Ngawi   2021           873346
21   Kabupaten Bojonegoro   2021          1307602
22        Kabupaten Tuban   2021          1203127
23     Kabupaten Lamongan   2021          1356027
24       Kabupaten Gresik   2021          1320570
25    Kabupaten Bangkalan   2021          1071712
26      Kabupaten Sampang   2021           976020
27    Kabupaten Pamekasan   2021           853507
28      Kabupaten Sumenep   2021          1129822
29            Kota Kediri   2021           287962
30            Kota Blitar   2021           150371
31            Kota Malang   2021           844933
32       Kota Probolinggo   2021           241202
33          Kota Pasuruan   2021           209528
34         Kota Mojokerto   2021           133272
35            Kota Madiun   2021           196917
36          Kota Surabaya   2021          2880284
37              Kota Batu   2021           214653

AMBIL DATA 2022

In [36]:
import pandas as pd

# 1. Baca data
df = pd.read_csv(
    "Jumlah Penduduk Menurut Jenis Kelamin dan Kabupaten_Kota Provinsi Jawa Timur, 2022.csv"
)

# 2. Rename kolom (karena header-nya berantakan)
df.columns = [
    'nama_kabupaten_kota',
    'laki_laki',
    'perempuan',
    'total_existing'
]

# 3. Buang baris header tambahan
df = df.iloc[3:].reset_index(drop=True)

# 4. Ubah ke numerik
df['laki_laki'] = pd.to_numeric(df['laki_laki'], errors='coerce')
df['perempuan'] = pd.to_numeric(df['perempuan'], errors='coerce')

# 5. Hitung jumlah penduduk
df['jumlah_penduduk'] = df['laki_laki'] + df['perempuan']

# 6. Ambil kolom final
df_penduduk_2022 = df[['nama_kabupaten_kota', 'jumlah_penduduk']]

df_penduduk_2022 = df_penduduk_2022[
    df_penduduk_2022['nama_kabupaten_kota'].str.strip().str.lower() != 'jawa timur'
]

# Tambahkan kolom tahun
df_penduduk_2022['tahun'] = 2022

df_penduduk_2022 = df_penduduk_2022[
    ['nama_kabupaten_kota', 'tahun', 'jumlah_penduduk']
]

df_penduduk_2022

      nama_kabupaten_kota  tahun  jumlah_penduduk
0       Kabupaten Pacitan   2022           592916
1      Kabupaten Ponorogo   2022           964253
2    Kabupaten Trenggalek   2022           739669
3   Kabupaten Tulungagung   2022          1105337
4        Kabupaten Blitar   2022          1240322
5        Kabupaten Kediri   2022          1656020
6        Kabupaten Malang   2022          2685900
7      Kabupaten Lumajang   2022          1137227
8        Kabupaten Jember   2022          2567718
9    Kabupaten Banyuwangi   2022          1731731
10    Kabupaten Bondowoso   2022           781417
11    Kabupaten Situbondo   2022           691260
12  Kabupaten Probolinggo   2022          1159965
13     Kabupaten Pasuruan   2022          1619035
14     Kabupaten Sidoarjo   2022          2103401
15    Kabupaten Mojokerto   2022          1133584
16      Kabupaten Jombang   2022          1335972
17      Kabupaten Nganjuk   2022          1117033
18       Kabupaten Madiun   2022           757665
19      Kabupaten Magetan   2022           678343
20        Kabupaten Ngawi   2022           877432
21   Kabupaten Bojonegoro   2022          1315125
22        Kabupaten Tuban   2022          1209543
23     Kabupaten Lamongan   2022          1371509
24       Kabupaten Gresik   2022          1332664
25    Kabupaten Bangkalan   2022          1086620
26      Kabupaten Sampang   2022           984162
27    Kabupaten Pamekasan   2022           857818
28      Kabupaten Sumenep   2022          1136632
29            Kota Kediri   2022           289418
30            Kota Blitar   2022           151960
31            Kota Malang   2022           846126
32       Kota Probolinggo   2022           243200
33          Kota Pasuruan   2022           211497
34         Kota Mojokerto   2022           134350
35            Kota Madiun   2022           199192
36          Kota Surabaya   2022          2887223
37              Kota Batu   2022           216735

AMBIL DATA 2023

In [37]:
import pandas as pd

# 1. Baca data
df = pd.read_csv(
    "Jumlah Penduduk Menurut Jenis Kelamin dan Kabupaten_Kota Provinsi Jawa Timur, 2023.csv"
)

# 2. Rename kolom (karena header-nya berantakan)
df.columns = [
    'nama_kabupaten_kota',
    'laki_laki',
    'perempuan',
    'total_existing'
]

# 3. Buang baris header tambahan
df = df.iloc[3:].reset_index(drop=True)

# 4. Ubah ke numerik
df['laki_laki'] = pd.to_numeric(df['laki_laki'], errors='coerce')
df['perempuan'] = pd.to_numeric(df['perempuan'], errors='coerce')

# 5. Hitung jumlah penduduk
df['jumlah_penduduk'] = df['laki_laki'] + df['perempuan']

# 6. Ambil kolom final
df_penduduk_2023 = df[['nama_kabupaten_kota', 'jumlah_penduduk']]

df_penduduk_2023 = df_penduduk_2023[
    df_penduduk_2023['nama_kabupaten_kota'].str.strip().str.lower() != 'jawa timur'
]

# Tambahkan kolom tahun
df_penduduk_2023['tahun'] = 2023

df_penduduk_2023 = df_penduduk_2023[
    ['nama_kabupaten_kota', 'tahun', 'jumlah_penduduk']
]

df_penduduk_2023

      nama_kabupaten_kota  tahun  jumlah_penduduk
0       Kabupaten Pacitan   2023           596649
1      Kabupaten Ponorogo   2023           972582
2    Kabupaten Trenggalek   2023           744358
3   Kabupaten Tulungagung   2023          1113973
4        Kabupaten Blitar   2023          1249497
5        Kabupaten Kediri   2023          1667450
6        Kabupaten Malang   2023          2703175
7      Kabupaten Lumajang   2023          1147261
8        Kabupaten Jember   2023          2584771
9    Kabupaten Banyuwangi   2023          1744814
10    Kabupaten Bondowoso   2023           784192
11    Kabupaten Situbondo   2023           694081
12  Kabupaten Probolinggo   2023          1163859
13     Kabupaten Pasuruan   2023          1626029
14     Kabupaten Sidoarjo   2023          2114588
15    Kabupaten Mojokerto   2023          1141516
16      Kabupaten Jombang   2023          1345886
17      Kabupaten Nganjuk   2023          1124247
18       Kabupaten Madiun   2023           765135
19      Kabupaten Magetan   2023           682466
20        Kabupaten Ngawi   2023           881393
21   Kabupaten Bojonegoro   2023          1322474
22        Kabupaten Tuban   2023          1215795
23     Kabupaten Lamongan   2023          1386941
24       Kabupaten Gresik   2023          1344648
25    Kabupaten Bangkalan   2023          1101556
26      Kabupaten Sampang   2023           992210
27    Kabupaten Pamekasan   2023           862009
28      Kabupaten Sumenep   2023          1143295
29            Kota Kediri   2023           290836
30            Kota Blitar   2023           153541
31            Kota Malang   2023           847182
32       Kota Probolinggo   2023           245174
33          Kota Pasuruan   2023           213450
34         Kota Mojokerto   2023           135414
35            Kota Madiun   2023           201460
36          Kota Surabaya   2023          2893698
37              Kota Batu   2023           218802

AMBIL DATA 2024

In [38]:
import pandas as pd

# 1. BACA DATA
df = pd.read_csv('lj_prtmbhn_dn_kpdtn_pnddk_mnrt_kbptn_kt_cl.csv')

# 2. STANDARISASI
df.columns = df.columns.str.strip().str.lower()

df['kategori'] = df['kategori'].str.lower().str.strip()
df['kabupatenkota'] = df['kabupatenkota'].str.title().str.strip()

df['jumlah'] = pd.to_numeric(df['jumlah'], errors='coerce')
df['tahun'] = df['tahun'].astype(int)

# 3. AMBIL HANYA JUMLAH PENDUDUK
df_penduduk_2024 = df[df['kategori'] == 'jumlah_penduduk']

# 4. PILIH KOLOM YANG DIPERLUKAN
df_penduduk_2024 = df_penduduk_2024[
    ['tahun', 'kabupatenkota', 'jumlah']
].rename(columns={
    'kabupatenkota': 'nama_kabupaten_kota',
    'jumlah': 'jumlah_penduduk'
})

# 5. FILTER TAHUN 2024
df_penduduk_2024 = df_penduduk_2024[
    df_penduduk_2024['tahun'] == 2024
]

# 6. HAPUS DATA PROVINSI (JAWA TIMUR)
df_penduduk_2024 = df_penduduk_2024[
    df_penduduk_2024['nama_kabupaten_kota'] != 'Jawa Timur'
]

# 7. SIAPKAN DATA TAHUN SEBELUMNYA (2023)
df_prev = df_penduduk_2023[
    ['nama_kabupaten_kota', 'jumlah_penduduk']
].rename(columns={
    'jumlah_penduduk': 'jumlah_penduduk_prev'
})

# 8. UBAH RIBU JIWA KE SATUAN JIWA (HANDLING BY 2 ANGKA TERAKHIR TAHUN SEBELUMNYA)
df_penduduk_2024 = df_penduduk_2024.merge(
    df_prev,
    on='nama_kabupaten_kota',
    how='left'
)
df_penduduk_2024['jumlah_penduduk'] = (
    (df_penduduk_2024['jumlah_penduduk'] * 1000)
    .astype(int)
    // 100 * 100
    +
    (df_penduduk_2024['jumlah_penduduk_prev'] % 100)
)

#9. SORT
df_penduduk_2024 = df_penduduk_2024[
    ['nama_kabupaten_kota', 'tahun', 'jumlah_penduduk']
]

df_penduduk_2024

      nama_kabupaten_kota  tahun  jumlah_penduduk
0       Kabupaten Pacitan   2024           588649
1      Kabupaten Ponorogo   2024           962982
2    Kabupaten Trenggalek   2024           744558
3   Kabupaten Tulungagung   2024          1113973
4        Kabupaten Blitar   2024          1263797
5        Kabupaten Kediri   2024          1689950
6        Kabupaten Malang   2024          2736075
7      Kabupaten Lumajang   2024          1145961
8        Kabupaten Jember   2024          2603871
9    Kabupaten Banyuwangi   2024          1754414
10    Kabupaten Bondowoso   2024           792392
11    Kabupaten Situbondo   2024           700781
12  Kabupaten Probolinggo   2024          1185259
13     Kabupaten Pasuruan   2024          1657229
14     Kabupaten Sidoarjo   2024          2171588
15    Kabupaten Mojokerto   2024          1154316
16      Kabupaten Jombang   2024          1362786
17      Kabupaten Nganjuk   2024          1131847
18       Kabupaten Madiun   2024           757835
19      Kabupaten Magetan   2024           685566
20        Kabupaten Ngawi   2024           884193
21   Kabupaten Bojonegoro   2024          1325374
22        Kabupaten Tuban   2024          1225295
23     Kabupaten Lamongan   2024          1378241
24       Kabupaten Gresik   2024          1364048
25    Kabupaten Bangkalan   2024          1102556
26      Kabupaten Sampang   2024          1016310
27    Kabupaten Pamekasan   2024           884709
28      Kabupaten Sumenep   2024          1153295
29            Kota Kediri   2024           298236
30            Kota Blitar   2024           154941
31            Kota Malang   2024           872782
32       Kota Probolinggo   2024           249574
33          Kota Pasuruan   2024           219450
34         Kota Mojokerto   2024           137414
35            Kota Madiun   2024           201860
36          Kota Surabaya   2024          2922098
37              Kota Batu   2024           222702

In [39]:
df_penduduk_2018.shape
df_penduduk_2019.shape
df_penduduk_2020.shape
df_penduduk_2021.shape
df_penduduk_2022.shape
df_penduduk_2023.shape
df_penduduk_2024.shape

(38, 3)

GABUNGKAN SELURUH DATA TAHUN 2018-2024

In [40]:
df_penduduk_all = pd.concat(
    [
        df_penduduk_2018,
        df_penduduk_2019,
        df_penduduk_2020,
        df_penduduk_2021,
        df_penduduk_2022,
        df_penduduk_2023,
        df_penduduk_2024
    ],
    ignore_index=True
)

df_penduduk_all

       nama_kabupaten_kota  tahun  jumlah_penduduk
0        Kabupaten Pacitan   2018           554394
1       Kabupaten Ponorogo   2018           870705
2     Kabupaten Trenggalek   2018           694902
3    Kabupaten Tulungagung   2018          1035290
4         Kabupaten Blitar   2018          1157500
..                     ...    ...              ...
261          Kota Pasuruan   2024           219450
262         Kota Mojokerto   2024           137414
263            Kota Madiun   2024           201860
264          Kota Surabaya   2024          2922098
265              Kota Batu   2024           222702

[266 rows x 3 columns]

ISI KODE KABUPATEN KOTA

In [41]:
import pandas as pd

# =====================================================
# A. DATA MASTER KODE WILAYAH 
# =====================================================

df_master = pd.read_csv('jumlah_tenaga_kesehatan.csv')

# rapikan nama kolom
df_master.columns = df_master.columns.str.strip()

# standarisasi nama kabupaten
df_master['nama_kabupaten_kota'] = (
    df_master['nama_kabupaten_kota']
    .astype(str)
    .str.strip()
    .str.upper()
)

# ambil mapping
master_kabkot = (
    df_master[['kode_kabupaten_kota', 'nama_kabupaten_kota']]
    .drop_duplicates()
)

master_kabkot

     kode_kabupaten_kota    nama_kabupaten_kota
0                   3501      KABUPATEN PACITAN
15                  3502     KABUPATEN PONOROGO
30                  3503   KABUPATEN TRENGGALEK
45                  3504  KABUPATEN TULUNGAGUNG
60                  3505       KABUPATEN BLITAR
75                  3506       KABUPATEN KEDIRI
90                  3507       KABUPATEN MALANG
105                 3508     KABUPATEN LUMAJANG
120                 3509       KABUPATEN JEMBER
135                 3510   KABUPATEN BANYUWANGI
150                 3511    KABUPATEN BONDOWOSO
165                 3512    KABUPATEN SITUBONDO
180                 3513  KABUPATEN PROBOLINGGO
195                 3514     KABUPATEN PASURUAN
210                 3515     KABUPATEN SIDOARJO
225                 3516    KABUPATEN MOJOKERTO
240                 3517      KABUPATEN JOMBANG
255                 3518      KABUPATEN NGANJUK
270                 3519       KABUPATEN MADIUN
285                 3520      KABUPATEN MAGETAN
300                 3521        KABUPATEN NGAWI
315                 3522   KABUPATEN BOJONEGORO
330                 3523        KABUPATEN TUBAN
345                 3524     KABUPATEN LAMONGAN
360                 3525       KABUPATEN GRESIK
375                 3526    KABUPATEN BANGKALAN
390                 3527      KABUPATEN SAMPANG
405                 3528    KABUPATEN PAMEKASAN
420                 3529      KABUPATEN SUMENEP
435                 3571            KOTA KEDIRI
450                 3572            KOTA BLITAR
465                 3573            KOTA MALANG
480                 3574       KOTA PROBOLINGGO
495                 3575          KOTA PASURUAN
510                 3576         KOTA MOJOKERTO
525                 3577            KOTA MADIUN
540                 3578          KOTA SURABAYA
555                 3579              KOTA BATU

In [42]:
# =====================================================
# B. SAMAKAN FORMAT NAMA KAB/KOTA
# =====================================================
df_penduduk_all['nama_kabupaten_kota'] = (
    df_penduduk_all['nama_kabupaten_kota']
    .str.strip()
    .str.title()
)

master_kabkot['nama_kabupaten_kota'] = (
    master_kabkot['nama_kabupaten_kota']
    .str.strip()
    .str.title()
)

In [43]:
# =====================================================
# C. MERGE KODE KABUPATEN 
# =====================================================

# pastikan data TIDAK punya kolom kode
df_penduduk_all = df_penduduk_all.drop(
    columns=['kode_kabupaten_kota'],
    errors='ignore'
)

# merge
df_penduduk_all = df_penduduk_all.merge(
    master_kabkot,
    on='nama_kabupaten_kota',
    how='left'
)

# =====================================================
# D. FORMAT AKHIR
# =====================================================

df_penduduk_all = df_penduduk_all.sort_values(
    ['tahun', 'kode_kabupaten_kota']
).reset_index(drop=True)

# kembalikan format penulisan
df_penduduk_all['nama_kabupaten_kota'] = (
    df_penduduk_all['nama_kabupaten_kota']
    .str.title()
)
df_penduduk_all = df_penduduk_all[
    [
        'kode_kabupaten_kota',
        'nama_kabupaten_kota',
        'tahun',
        'jumlah_penduduk'
    ]
]

df_penduduk_all

     kode_kabupaten_kota    nama_kabupaten_kota  tahun  jumlah_penduduk
0                   3501      Kabupaten Pacitan   2018           554394
1                   3502     Kabupaten Ponorogo   2018           870705
2                   3503   Kabupaten Trenggalek   2018           694902
3                   3504  Kabupaten Tulungagung   2018          1035290
4                   3505       Kabupaten Blitar   2018          1157500
..                   ...                    ...    ...              ...
261                 3575          Kota Pasuruan   2024           219450
262                 3576         Kota Mojokerto   2024           137414
263                 3577            Kota Madiun   2024           201860
264                 3578          Kota Surabaya   2024          2922098
265                 3579              Kota Batu   2024           222702

[266 rows x 4 columns]

SIMPAN DATA CSV

In [44]:
df_penduduk_all.to_csv('data_penduduk.csv', index=False)