# Data Jumlah Puskesmas #

In [1]:
import pandas as pd

# ==============================================================================
# DATA
# ==============================================================================
df_puskesmas = pd.read_csv('data_jumlah_puskesmas.csv')

print("=========== DATA ===========")
df_puskesmas

=========== DATA ===========

,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,tahun,PELAYANAN_NON_RAWAT_INAP,PELAYANAN_RAWAT_INAP
0,35,JAWA TIMUR,3501,KABUPATEN PACITAN,2018,9,15
1,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2018,12,19
2,35,JAWA TIMUR,3503,KABUPATEN TRENGGALEK,2018,3,19
3,35,JAWA TIMUR,3504,KABUPATEN TULUNGAGUNG,2018,14,18
4,35,JAWA TIMUR,3505,KABUPATEN BLITAR,2018,6,18
...,...,...,...,...,...,...,...
261,35,JAWA TIMUR,3575,KOTA PASURUAN,2024,8,0
262,35,JAWA TIMUR,3576,KOTA MOJOKERTO,2024,6,0
263,35,JAWA TIMUR,3577,KOTA MADIUN,2024,6,0
264,35,JAWA TIMUR,3578,KOTA SURABAYA,2024,40,23
265,35,JAWA TIMUR,3579,KOTA BATU,2024,2,3

In [18]:
# Pivot Rawat Inap
df_rawat_inap = df_puskesmas.pivot_table(
    index= ['kode_kabupaten_kota', 'nama_kabupaten_kota'],
    columns='tahun',
    values='PELAYANAN_RAWAT_INAP',
    aggfunc='sum'
).reset_index()

df_rawat_inap.columns.name = None
df_rawat_inap.head(10)

,kode_kabupaten_kota,nama_kabupaten_kota,2018,2019,2020,2021,2022,2023,2024
0,3501,KABUPATEN PACITAN,15,15,15,15,15,15,15
1,3502,KABUPATEN PONOROGO,19,19,19,19,19,19,18
2,3503,KABUPATEN TRENGGALEK,19,19,19,20,20,20,19
3,3504,KABUPATEN TULUNGAGUNG,18,18,18,17,17,17,17
4,3505,KABUPATEN BLITAR,18,18,18,18,18,18,15
5,3506,KABUPATEN KEDIRI,8,8,8,8,8,8,8
6,3507,KABUPATEN MALANG,39,39,39,39,39,39,39
7,3508,KABUPATEN LUMAJANG,22,22,22,25,25,25,25
8,3509,KABUPATEN JEMBER,17,17,17,43,43,43,43
9,3510,KABUPATEN BANYUWANGI,19,19,19,18,18,18,18

In [19]:
# Pivot Non Rawat Inap
df_non_rawat_inap = df_puskesmas.pivot_table(
    index= ['kode_kabupaten_kota', 'nama_kabupaten_kota'],
    columns='tahun',
    values='PELAYANAN_NON_RAWAT_INAP',
    aggfunc='sum'
).reset_index()

df_non_rawat_inap.columns.name = None
df_non_rawat_inap.head(10)

,kode_kabupaten_kota,nama_kabupaten_kota,2018,2019,2020,2021,2022,2023,2024
0,3501,KABUPATEN PACITAN,9,9,9,9,9,9,9
1,3502,KABUPATEN PONOROGO,12,12,12,12,12,12,13
2,3503,KABUPATEN TRENGGALEK,3,3,3,2,2,2,3
3,3504,KABUPATEN TULUNGAGUNG,14,14,14,15,15,15,15
4,3505,KABUPATEN BLITAR,6,6,6,6,6,6,9
5,3506,KABUPATEN KEDIRI,29,29,29,29,29,29,29
6,3507,KABUPATEN MALANG,0,0,0,0,0,0,0
7,3508,KABUPATEN LUMAJANG,3,3,3,0,0,0,0
8,3509,KABUPATEN JEMBER,33,33,33,7,7,7,7
9,3510,KABUPATEN BANYUWANGI,26,26,26,27,27,27,27

# Data jumlah Penyakit Menular

In [21]:
import pandas as pd

# ==============================================================================
# DATA
# ==============================================================================
df_penyakitmenular = pd.read_csv('data_jumlah_penyakitmenular.csv')

print("=========== DATA ===========")
df_penyakitmenular

=========== DATA ===========

,kode_kabupaten_kota,nama_kabupaten_kota,tahun,JUMLAH_PENYAKIT_MENULAR
0,3501,KABUPATEN PACITAN,2018,292
1,3502,KABUPATEN PONOROGO,2018,479
2,3503,KABUPATEN TRENGGALEK,2018,285
3,3504,KABUPATEN TULUNGAGUNG,2018,507
4,3505,KABUPATEN BLITAR,2018,392
...,...,...,...,...
261,3575,KOTA PASURUAN,2024,287
262,3576,KOTA MOJOKERTO,2024,129
263,3577,KOTA MADIUN,2024,756
264,3578,KOTA SURABAYA,2024,2299
265,3579,KOTA BATU,2024,511

In [22]:
# Pivot Penyakit Menular
df_penyakitmenular = df_penyakitmenular.pivot_table(
    index= ['kode_kabupaten_kota', 'nama_kabupaten_kota'],
    columns='tahun',
    values='JUMLAH_PENYAKIT_MENULAR',
    aggfunc='sum'
).reset_index()

df_penyakitmenular.columns.name = None
df_penyakitmenular.head(10)

,kode_kabupaten_kota,nama_kabupaten_kota,2018,2019,2020,2021,2022,2023,2024
0,3501,KABUPATEN PACITAN,292,670,1503,7600,2235,322,553
1,3502,KABUPATEN PONOROGO,479,1842,1538,11496,3116,414,632
2,3503,KABUPATEN TRENGGALEK,285,613,1448,7331,2313,379,1166
3,3504,KABUPATEN TULUNGAGUNG,507,1288,1878,7423,3424,734,1832
4,3505,KABUPATEN BLITAR,392,856,2123,9261,3279,755,1590
5,3506,KABUPATEN KEDIRI,516,1668,2946,12133,9069,982,837
6,3507,KABUPATEN MALANG,803,1970,3182,13586,15346,2007,4666
7,3508,KABUPATEN LUMAJANG,222,1097,3457,6813,3845,893,1350
8,3509,KABUPATEN JEMBER,611,2083,6227,12929,7706,1755,2462
9,3510,KABUPATEN BANYUWANGI,74,789,4861,10192,7622,1049,1075

# Data Jumlah Penyakit Tidak Menular

In [23]:
import pandas as pd

# ==============================================================================
# DATA
# ==============================================================================
df_penyakittidakmenular = pd.read_csv('data_jumlah_penyakittidakmenular.csv')

print("=========== DATA ===========")
df_penyakittidakmenular

=========== DATA ===========

,kode_kabupaten_kota,nama_kabupaten_kota,tahun,JUMLAH_PENYAKIT_TIDAK_MENULAR
0,3501,KABUPATEN PACITAN,2018,41173
1,3502,KABUPATEN PONOROGO,2018,46778
2,3503,KABUPATEN TRENGGALEK,2018,40464
3,3504,KABUPATEN TULUNGAGUNG,2018,114929
4,3505,KABUPATEN BLITAR,2018,65232
...,...,...,...,...
261,3575,KOTA PASURUAN,2024,18844
262,3576,KOTA MOJOKERTO,2024,16010
263,3577,KOTA MADIUN,2024,23764
264,3578,KOTA SURABAYA,2024,851331
265,3579,KOTA BATU,2024,58862

In [24]:
# Pivot Penyakit Tidak Menular
df_penyakittidakmenular = df_penyakittidakmenular.pivot_table(
    index= ['kode_kabupaten_kota', 'nama_kabupaten_kota'],
    columns='tahun',
    values='JUMLAH_PENYAKIT_TIDAK_MENULAR',
    aggfunc='sum'
).reset_index()

df_penyakittidakmenular.columns.name = None
df_penyakittidakmenular.head(10)

,kode_kabupaten_kota,nama_kabupaten_kota,2018,2019,2020,2021,2022,2023,2024
0,3501,KABUPATEN PACITAN,41173,29288,46806,99,96220,99836,124298
1,3502,KABUPATEN PONOROGO,46778,61691,55887,31,83167,149775,172338
2,3503,KABUPATEN TRENGGALEK,40464,72714,80120,51,214529,224076,64480
3,3504,KABUPATEN TULUNGAGUNG,114929,71059,84288,31,136041,258200,296597
4,3505,KABUPATEN BLITAR,65232,216193,142546,88,352263,390004,391130
5,3506,KABUPATEN KEDIRI,43288,109213,62406,114,178368,439943,120174
6,3507,KABUPATEN MALANG,296972,229420,188607,129,250173,830242,247869
7,3508,KABUPATEN LUMAJANG,64334,149053,103121,89,144578,230032,274601
8,3509,KABUPATEN JEMBER,81963,392779,219352,200,306496,198428,184554
9,3510,KABUPATEN BANYUWANGI,175108,372277,278525,365,352612,455903,132739

# Data Jumlah Tenaga Kesehatan

In [30]:
import pandas as pd

# ==============================================================================
# DATA
# ==============================================================================
df_tenagakesehatan = pd.read_csv('data_jumlah_tenagakesehatan.csv')

print("=========== DATA ===========")
df_tenagakesehatan

=========== DATA ===========

,kode_kabupaten_kota,nama_kabupaten_kota,tahun,JUMLAH_BIDAN,JUMLAH_DOKTER,JUMLAH_PERAWAT
0,3501,KABUPATEN PACITAN,2018,347,141,619
1,3502,KABUPATEN PONOROGO,2018,519,129,990
2,3503,KABUPATEN TRENGGALEK,2018,384,227,792
3,3504,KABUPATEN TULUNGAGUNG,2018,609,263,1098
4,3505,KABUPATEN BLITAR,2018,540,233,837
...,...,...,...,...,...,...
261,3575,KOTA PASURUAN,2024,1,0,261
262,3576,KOTA MOJOKERTO,2024,4,0,396
263,3577,KOTA MADIUN,2024,5,0,521
264,3578,KOTA SURABAYA,2024,69,0,7446
265,3579,KOTA BATU,2024,4,0,303

In [31]:
# Pivot tenaga Kesehatan Bidan
df_tenagakesehatan_bidan = df_tenagakesehatan.pivot_table(
    index= ['kode_kabupaten_kota', 'nama_kabupaten_kota'],
    columns='tahun',
    values='JUMLAH_BIDAN',
    aggfunc='sum'
).reset_index()

df_tenagakesehatan_bidan.columns.name = None
df_tenagakesehatan_bidan.head(10)

,kode_kabupaten_kota,nama_kabupaten_kota,2018,2019,2020,2021,2022,2023,2024
0,3501,KABUPATEN PACITAN,347,346,374,411,434,412,3
1,3502,KABUPATEN PONOROGO,519,565,609,755,828,759,4
2,3503,KABUPATEN TRENGGALEK,384,395,398,460,462,491,0
3,3504,KABUPATEN TULUNGAGUNG,609,635,609,1051,1029,1038,2
4,3505,KABUPATEN BLITAR,540,427,561,686,728,731,6
5,3506,KABUPATEN KEDIRI,709,677,828,987,990,926,3
6,3507,KABUPATEN MALANG,573,951,862,1316,1382,1369,17
7,3508,KABUPATEN LUMAJANG,416,541,590,859,799,796,2
8,3509,KABUPATEN JEMBER,1060,1065,1082,1625,1637,1629,6
9,3510,KABUPATEN BANYUWANGI,953,912,1093,1218,1161,1139,5

In [32]:
# Pivot tenaga Kesehatan Dokter
df_tenagakesehatan_dokter = df_tenagakesehatan.pivot_table(
    index= ['kode_kabupaten_kota', 'nama_kabupaten_kota'],
    columns='tahun',
    values='JUMLAH_DOKTER',
    aggfunc='sum'
).reset_index()

df_tenagakesehatan_dokter.columns.name = None
df_tenagakesehatan_dokter.head(10)

,kode_kabupaten_kota,nama_kabupaten_kota,2018,2019,2020,2021,2022,2023,2024
0,3501,KABUPATEN PACITAN,141,99,89,136,93,0,0
1,3502,KABUPATEN PONOROGO,129,108,147,300,258,0,0
2,3503,KABUPATEN TRENGGALEK,227,145,98,148,124,0,0
3,3504,KABUPATEN TULUNGAGUNG,263,232,231,402,279,0,0
4,3505,KABUPATEN BLITAR,233,174,184,294,214,0,0
5,3506,KABUPATEN KEDIRI,380,195,256,421,322,0,0
6,3507,KABUPATEN MALANG,169,344,345,652,608,0,0
7,3508,KABUPATEN LUMAJANG,105,121,141,346,204,0,0
8,3509,KABUPATEN JEMBER,150,179,282,654,436,0,0
9,3510,KABUPATEN BANYUWANGI,207,308,316,604,342,0,0

In [33]:
# Pivot tenaga Kesehatan Perawat
df_tenagakesehatan_perawat = df_tenagakesehatan.pivot_table(
    index= ['kode_kabupaten_kota', 'nama_kabupaten_kota'],
    columns='tahun',
    values='JUMLAH_PERAWAT',
    aggfunc='sum'
).reset_index()

df_tenagakesehatan_perawat.columns.name = None
df_tenagakesehatan_perawat.head(10)

,kode_kabupaten_kota,nama_kabupaten_kota,2018,2019,2020,2021,2022,2023,2024
0,3501,KABUPATEN PACITAN,619,624,629,593,756,738,185
1,3502,KABUPATEN PONOROGO,990,1218,1370,1457,1548,1629,445
2,3503,KABUPATEN TRENGGALEK,792,917,894,886,1026,1032,233
3,3504,KABUPATEN TULUNGAGUNG,1098,1658,1463,1820,2186,2259,589
4,3505,KABUPATEN BLITAR,837,870,848,775,1098,1186,455
5,3506,KABUPATEN KEDIRI,981,1051,1315,1381,1651,1632,753
6,3507,KABUPATEN MALANG,1291,2661,2735,2791,3664,3698,1671
7,3508,KABUPATEN LUMAJANG,990,1172,1343,1412,1538,1600,435
8,3509,KABUPATEN JEMBER,2010,2039,2305,2130,2973,2996,921
9,3510,KABUPATEN BANYUWANGI,1342,1693,1759,1525,1958,2010,705

# Data Jumlah Penduduk

In [34]:
import pandas as pd

# ==============================================================================
# DATA
# ==============================================================================
df_penduduk = pd.read_csv('data_jumlah_penduduk.csv')

print("=========== DATA ===========")
df_penduduk

=========== DATA ===========

,Unnamed: 0,kode_kabupaten_kota,nama_kabupaten_kota,tahun,JUMLAH_PENDUDUK
0,0,3501,KABUPATEN PACITAN,2018,592938
1,1,3502,KABUPATEN PONOROGO,2018,962125
2,2,3503,KABUPATEN TRENGGALEK,2018,748432
3,3,3504,KABUPATEN TULUNGAGUNG,2018,1109547
4,4,3505,KABUPATEN BLITAR,2018,1230159
...,...,...,...,...,...
261,261,3575,KOTA PASURUAN,2024,213469
262,262,3576,KOTA MOJOKERTO,2024,142272
263,263,3577,KOTA MADIUN,2024,201733
264,264,3578,KOTA SURABAYA,2024,3018022
265,265,3579,KOTA BATU,2024,225408

In [35]:
# Pivot Penduduk
df_penduduk = df_penduduk.pivot_table(
    index='nama_kabupaten_kota',
    columns='tahun',
    values='JUMLAH_PENDUDUK',
    aggfunc='sum'
).reset_index()

df_penduduk.columns.name = None
df_penduduk.head(10)

,nama_kabupaten_kota,2018,2019,2020,2021,2022,2023,2024
0,KABUPATEN BANGKALAN,1066890,1076333,1082656,1083192,1039288,1047306,1042031
1,KABUPATEN BANYUWANGI,1733027,1747663,1754719,1750778,1762181,1780015,1791789
2,KABUPATEN BLITAR,1230159,1246653,1249190,1229275,1239565,1252242,1261699
3,KABUPATEN BOJONEGORO,1325739,1335840,1343659,1342434,1350650,1363058,1366227
4,KABUPATEN BONDOWOSO,793271,797592,801425,802102,802864,796911,788007
5,KABUPATEN GRESIK,1265268,1275063,1283826,1284158,1291518,1304203,1327497
6,KABUPATEN JEMBER,2556614,2568884,2578949,2582673,2585275,2600663,2615874
7,KABUPATEN JOMBANG,1325122,1343212,1350105,1351420,1359332,1370510,1378005
8,KABUPATEN KEDIRI,1647835,1662508,1673569,1673158,1674818,1684454,1691976
9,KABUPATEN LAMONGAN,1361312,1373390,1379628,1380145,1381414,1385835,1367503

# Simpan Data satu Excel

In [36]:
import pandas as pd

# Nama file Excel
nama_file = 'dataset_pivot.xlsx'

with pd.ExcelWriter(nama_file, engine='openpyxl') as writer:

    # Sheet 1
    df_rawat_inap.to_excel(
        writer,
        sheet_name='Rawat_Inap',
        index=False
    )

    # Sheet 2
    df_non_rawat_inap.to_excel(
        writer,
        sheet_name='Non_Rawat_Inap',
        index=False
    )

    # Sheet 3
    df_penyakitmenular.to_excel(
        writer,
        sheet_name='Penyakit_Menular',
        index=False
    )

    # Sheet 4
    df_penyakittidakmenular.to_excel(
        writer,
        sheet_name='Penyakit_Tidak_Menular',
        index=False
    )

    # Sheet 5
    df_tenagakesehatan_bidan.to_excel(
        writer,
        sheet_name='Tenaga_Kesehatan_Bidan',
        index=False
    )

    # Sheet 6
    df_tenagakesehatan_dokter.to_excel(
        writer,
        sheet_name='Tenaga_Kesehatan_Dokter',
        index=False
    )

# Sheet 7
    df_tenagakesehatan_perawat.to_excel(
        writer,
        sheet_name='Tenaga_Kesehatan_Perawat',
        index=False
    )

# Sheet 8
    df_penduduk.to_excel(
        writer,
        sheet_name='Penduduk',
        index=False
    )
print(f"File berhasil disimpan sebagai: {nama_file}")

File berhasil disimpan sebagai: dataset_pivot.xlsx