# KOMPARASI K-MEANS & AGGLOMERATIVE HIERARCHICAL CLUSTERING

In [7]:
import pandas as pd

# ==============================================================================
# DATA K-MEANS
# ==============================================================================
df_kmeans = pd.read_csv('data_clustering_kmeans_normalized.csv')
kolom_string = [
    'kode_provinsi',
    'kode_kabupaten_kota',
]

df_kmeans[kolom_string] = df_kmeans[kolom_string].astype(str)

kolom_numerik = [
    col for col in df_kmeans.select_dtypes(include='number').columns
    if col != 'tahun'
]

print("=========== DATA ===========")
df_kmeans

=========== DATA ===========

,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,tahun,pelayanan_non_rawat_inap,pelayanan_rawat_inap,jumlah_bidan,jumlah_dokter,jumlah_perawat,jumlah_penyakit_tidak_menular,jumlah_penyakit_menular,jumlah_penduduk,cluster,sub_cluster
0,35,JAWA TIMUR,3501,KABUPATEN PACITAN,2018,0.230769,-0.153846,-0.639716,-0.292108,-0.710573,-0.290467,-0.355131,-0.841177,1,1
1,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2018,0.461538,0.153846,-0.334074,-0.348645,-0.272298,-0.258875,-0.281465,-0.290178,1,1
2,35,JAWA TIMUR,3503,KABUPATEN TRENGGALEK,2018,-0.230769,0.153846,-0.573967,0.113074,-0.506202,-0.294463,-0.357889,-0.596418,1,1
3,35,JAWA TIMUR,3504,KABUPATEN TULUNGAGUNG,2018,0.615385,0.076923,-0.174145,0.282686,-0.144714,0.125248,-0.270435,-0.003479,1,1
4,35,JAWA TIMUR,3505,KABUPATEN BLITAR,2018,0.000000,0.076923,-0.296757,0.141343,-0.453042,-0.154862,-0.315738,0.209405,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,35,JAWA TIMUR,3575,KOTA PASURUAN,2024,0.153846,-1.307692,-0.749889,-0.089517,-0.767277,-0.416321,-0.357101,-1.424734,1,1
262,35,JAWA TIMUR,3576,KOTA MOJOKERTO,2024,0.000000,-1.307692,-0.810307,0.000000,-0.304194,-0.432294,-0.419342,-1.567573,1,1
263,35,JAWA TIMUR,3577,KOTA MADIUN,2024,0.000000,-1.307692,-0.618392,0.504122,0.273479,-0.388590,-0.172346,-1.455436,1,1
264,35,JAWA TIMUR,3578,KOTA SURABAYA,2024,2.615385,0.461538,2.427366,17.191991,12.351447,4.275868,0.435493,3.283073,1,2
265,35,JAWA TIMUR,3579,KOTA BATU,2024,-0.307692,-1.076923,-0.970235,-0.127208,-0.720024,-0.190765,-0.268860,-1.418998,1,1

In [8]:
import pandas as pd

# ==============================================================================
# DATA AGGLOMERATIVE HIERARCHICAL CLUSTERING (AHC)
# ==============================================================================
df_ahc = pd.read_csv('data_clustering_agglomerative_normalized.csv')
kolom_string = [
    'kode_provinsi',
    'kode_kabupaten_kota',
]

df_ahc[kolom_string] = df_ahc[kolom_string].astype(str)

kolom_numerik = [
    col for col in df_ahc.select_dtypes(include='number').columns
    if col != 'tahun'
]

print("=========== DATA ===========")
df_ahc

=========== DATA ===========

,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,tahun,pelayanan_non_rawat_inap,pelayanan_rawat_inap,jumlah_bidan,jumlah_dokter,jumlah_perawat,jumlah_penyakit_tidak_menular,jumlah_penyakit_menular,jumlah_penduduk,cluster,sub_cluster
0,35,JAWA TIMUR,3501,KABUPATEN PACITAN,2018,0.230769,-0.153846,-0.639716,-0.292108,-0.710573,-0.290467,-0.355131,-0.841177,1,1
1,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2018,0.461538,0.153846,-0.334074,-0.348645,-0.272298,-0.258875,-0.281465,-0.290178,1,1
2,35,JAWA TIMUR,3503,KABUPATEN TRENGGALEK,2018,-0.230769,0.153846,-0.573967,0.113074,-0.506202,-0.294463,-0.357889,-0.596418,1,1
3,35,JAWA TIMUR,3504,KABUPATEN TULUNGAGUNG,2018,0.615385,0.076923,-0.174145,0.282686,-0.144714,0.125248,-0.270435,-0.003479,1,1
4,35,JAWA TIMUR,3505,KABUPATEN BLITAR,2018,0.000000,0.076923,-0.296757,0.141343,-0.453042,-0.154862,-0.315738,0.209405,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,35,JAWA TIMUR,3575,KOTA PASURUAN,2024,0.153846,-1.307692,-0.749889,-0.089517,-0.767277,-0.416321,-0.357101,-1.424734,1,1
262,35,JAWA TIMUR,3576,KOTA MOJOKERTO,2024,0.000000,-1.307692,-0.810307,0.000000,-0.304194,-0.432294,-0.419342,-1.567573,1,1
263,35,JAWA TIMUR,3577,KOTA MADIUN,2024,0.000000,-1.307692,-0.618392,0.504122,0.273479,-0.388590,-0.172346,-1.455436,1,1
264,35,JAWA TIMUR,3578,KOTA SURABAYA,2024,2.615385,0.461538,2.427366,17.191991,12.351447,4.275868,0.435493,3.283073,1,3
265,35,JAWA TIMUR,3579,KOTA BATU,2024,-0.307692,-1.076923,-0.970235,-0.127208,-0.720024,-0.190765,-0.268860,-1.418998,1,1

In [9]:
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score

# ==========================================================
# PERBANDINGAN EVALUASI K-MEANS DAN AHC (K = 2)
# ==========================================================

# K-MEANS
silhouette_kmeans = silhouette_score(
    df_kmeans[kolom_numerik],
    df_kmeans['cluster']
)

dbi_kmeans = davies_bouldin_score(
    df_kmeans[kolom_numerik],
    df_kmeans['cluster']
)

chi_kmeans = calinski_harabasz_score(
    df_kmeans[kolom_numerik],
    df_kmeans['cluster']
)

# AHC
silhouette_ahc = silhouette_score(
    df_ahc[kolom_numerik],
    df_ahc['cluster']
)

dbi_ahc = davies_bouldin_score(
    df_ahc[kolom_numerik],
    df_ahc['cluster']
)

chi_ahc = calinski_harabasz_score(
    df_ahc[kolom_numerik],
    df_ahc['cluster']
)


# ==========================================================
# TABEL PERBANDINGAN
# ==========================================================

df_perbandingan = pd.DataFrame({
    'Metode': ['K-Means', 'AHC'],
    'Silhouette Score': [silhouette_kmeans, silhouette_ahc],
    'Davies-Bouldin Index': [dbi_kmeans, dbi_ahc],
    'Calinski-Harabasz Index': [chi_kmeans, chi_ahc]
})

print("========== PERBANDINGAN EVALUASI K=2 ==========")
df_perbandingan.round(4)

========== PERBANDINGAN EVALUASI K=2 ==========

    Metode  Silhouette Score  Davies-Bouldin Index  Calinski-Harabasz Index
0  K-Means            0.8888                0.2716                 196.6793
1      AHC            0.8885                0.2718                 195.1617

In [10]:
# ==========================================================
# PERBANDINGAN 
# ==========================================================

print("\n========== PERBANDINGAN ==========")

# Silhouette → semakin tinggi semakin baik
if silhouette_kmeans > silhouette_ahc:
    print("Silhouette Score : K-Means lebih tinggi")
elif silhouette_ahc > silhouette_kmeans:
    print("Silhouette Score : AHC lebih tinggi")
else:
    print("Silhouette Score : Nilai sama")


# DBI → semakin rendah semakin baik
if dbi_kmeans < dbi_ahc:
    print("Davies-Bouldin Index : K-Means lebih rendah")
elif dbi_ahc < dbi_kmeans:
    print("Davies-Bouldin Index : AHC lebih rendah")
else:
    print("Davies-Bouldin Index : Nilai sama")


# CH → semakin tinggi semakin baik
if chi_kmeans > chi_ahc:
    print("Calinski-Harabasz Index : K-Means lebih tinggi")
elif chi_ahc > chi_kmeans:
    print("Calinski-Harabasz Index : AHC lebih tinggi")
else:
    print("Calinski-Harabasz Index : Nilai sama")

========== PERBANDINGAN ==========
Silhouette Score : K-Means lebih tinggi
Davies-Bouldin Index : K-Means lebih rendah
Calinski-Harabasz Index : K-Means lebih tinggi

In [11]:
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score

# ==========================================================
# PERBANDINGAN EVALUASI K-MEANS DAN AHC (K = 2)
# ==========================================================

# K-MEANS
silhouette_kmeans = silhouette_score(
    df_kmeans[kolom_numerik],
    df_kmeans['sub_cluster']
)

dbi_kmeans = davies_bouldin_score(
    df_kmeans[kolom_numerik],
    df_kmeans['sub_cluster']
)

chi_kmeans = calinski_harabasz_score(
    df_kmeans[kolom_numerik],
    df_kmeans['sub_cluster']
)

# AHC
silhouette_ahc = silhouette_score(
    df_ahc[kolom_numerik],
    df_ahc['sub_cluster']
)

dbi_ahc = davies_bouldin_score(
    df_ahc[kolom_numerik],
    df_ahc['sub_cluster']
)

chi_ahc = calinski_harabasz_score(
    df_ahc[kolom_numerik],
    df_ahc['sub_cluster']
)


# ==========================================================
# TABEL PERBANDINGAN
# ==========================================================

df_perbandingan = pd.DataFrame({
    'Metode': ['K-Means', 'AHC'],
    'Silhouette Score': [silhouette_kmeans, silhouette_ahc],
    'Davies-Bouldin Index': [dbi_kmeans, dbi_ahc],
    'Calinski-Harabasz Index': [chi_kmeans, chi_ahc]
})

print("========== PERBANDINGAN EVALUASI K=2 ==========")
df_perbandingan.round(4)

========== PERBANDINGAN EVALUASI K=2 ==========

    Metode  Silhouette Score  Davies-Bouldin Index  Calinski-Harabasz Index
0  K-Means            0.8321                0.2986                 189.3802
1      AHC            0.5857                0.6968                 216.6768

In [12]:
# ==========================================================
# PERBANDINGAN 
# ==========================================================

print("\n========== PERBANDINGAN ==========")

# Silhouette → semakin tinggi semakin baik
if silhouette_kmeans > silhouette_ahc:
    print("Silhouette Score : K-Means lebih tinggi")
elif silhouette_ahc > silhouette_kmeans:
    print("Silhouette Score : AHC lebih tinggi")
else:
    print("Silhouette Score : Nilai sama")


# DBI → semakin rendah semakin baik
if dbi_kmeans < dbi_ahc:
    print("Davies-Bouldin Index : K-Means lebih rendah")
elif dbi_ahc < dbi_kmeans:
    print("Davies-Bouldin Index : AHC lebih rendah")
else:
    print("Davies-Bouldin Index : Nilai sama")


# CH → semakin tinggi semakin baik
if chi_kmeans > chi_ahc:
    print("Calinski-Harabasz Index : K-Means lebih tinggi")
elif chi_ahc > chi_kmeans:
    print("Calinski-Harabasz Index : AHC lebih tinggi")
else:
    print("Calinski-Harabasz Index : Nilai sama")

========== PERBANDINGAN ==========
Silhouette Score : K-Means lebih tinggi
Davies-Bouldin Index : K-Means lebih rendah
Calinski-Harabasz Index : AHC lebih tinggi