# DATA TENAGA KESEHATAN #

* DATA

_DATA 1_

In [424]:
import pandas as pd

# ==============================================================================
# DATA
# ==============================================================================

#-------------------------
# DATA 2018 - 2022
#-------------------------
df1_20182022 = pd.read_csv('jumlah_tenaga_kesehatan.csv')

print("=========== DATA 1 ===========")
df1_20182022

=========== DATA 1 ===========

,id,id_index,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,periode_update,kategori,jumlah,satuan,tahun
0,1,11,35,JAWA TIMUR,3501,KABUPATEN PACITAN,2018-S2,JUMLAH TENAGA DOKTER SPESIALIS,52,ORANG,2018
1,1,21,35,JAWA TIMUR,3501,KABUPATEN PACITAN,2018-S2,JUMLAH TENAGA KETEKNISAN MEDIS,75,ORANG,2018
2,1,31,35,JAWA TIMUR,3501,KABUPATEN PACITAN,2018-S2,JUMLAH TENAGA DOKTER GIGI,33,ORANG,2018
3,1,41,35,JAWA TIMUR,3501,KABUPATEN PACITAN,2018-S2,JUMLAH TENAGA PERAWAT,619,ORANG,2018
4,1,51,35,JAWA TIMUR,3501,KABUPATEN PACITAN,2018-S2,JUMLAH TENAGA KEFARMASIAN,50,ORANG,2018
...,...,...,...,...,...,...,...,...,...,...,...
2845,190,2846190,35,JAWA TIMUR,3579,KOTA BATU,2022-S2,JUMLAH TENAGA KESEHATAN MASYARAKAT,44,ORANG,2022
2846,190,2847190,35,JAWA TIMUR,3579,KOTA BATU,2022-S2,JUMLAH TENAGA KEFARMASIAN,170,ORANG,2022
2847,190,2848190,35,JAWA TIMUR,3579,KOTA BATU,2022-S2,JUMLAH TENAGA DOKTER SPESIALIS,57,ORANG,2022
2848,190,2849190,35,JAWA TIMUR,3579,KOTA BATU,2022-S2,JUMLAH TENAGA KESEHATAN LINGKUNGAN,11,ORANG,2022
2849,190,2850190,35,JAWA TIMUR,3579,KOTA BATU,2022-S2,JUMLAH TENAGA GIZI,35,ORANG,2022

_DATA 2_

In [425]:
# -------------------------
# DATA 2023 - 2024
# -------------------------
df2_20232024 = pd.read_csv('jumlah_tenaga_kesehatan_2023_2024.csv')

print("=========== DATA 2 ===========")
df2_20232024

=========== DATA 2 ===========

,no,kabupaten/kota,unit,tahun,dokter,keperawatan,kebidanan
0,1,KABUPATEN PACITAN,PUSKESMAS,2023,50,378,64
1,2,KABUPATEN PONOROGO,PUSKESMAS,2023,82,474,162
2,3,KABUPATEN TRENGGALEK,PUSKESMAS,2023,80,499,88
3,4,KABUPATEN TULUNGAGUNG,PUSKESMAS,2023,62,559,247
4,5,KABUPATEN BLITAR,PUSKESMAS,2023,67,307,143
...,...,...,...,...,...,...,...
223,224,KOTA PASURUAN,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2024,112,146,82
224,225,KOTA MOJOKERTO,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2024,83,94,59
225,226,KOTA MADIUN,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2024,142,151,49
226,227,KOTA SURABAYA,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2024,1359,1120,258
227,228,KOTA BATU,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2024,83,42,41

* DATA CLEANING

_DATA 1_

In [426]:
#===============================================================================
# DATA CLEANING 2018 - 2022
#===============================================================================

print("=========== DATA 1 CLEANING ===========")

df1_20182022 = df1_20182022[
    df1_20182022['kategori'].isin([
        'JUMLAH TENAGA DOKTER UMUM',
        'JUMLAH TENAGA PERAWAT',
        'JUMLAH TENAGA BIDAN'
    ])
].copy()

# -------------------------
# 1. INFO DATA
# -------------------------
print("\n 1. Info Data:")
df1_20182022.info()

print("\n Info Data Setelah Konversi ke String (selain jumlah dan tahun)")
kolom_string = [
    'id',
    'id_index',
    'kode_provinsi',
    'kode_kabupaten_kota',
    'periode_update'
]

df1_20182022[kolom_string] = df1_20182022[kolom_string].astype(str)
df1_20182022.info()

=========== DATA 1 CLEANING ===========

 1. Info Data:
<class 'pandas.core.frame.DataFrame'>
Index: 570 entries, 3 to 2842
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   570 non-null    int64
 1   id_index             570 non-null    int64
 2   kode_provinsi        570 non-null    int64
 3   nama_provinsi        570 non-null    object
 4   kode_kabupaten_kota  570 non-null    int64
 5   nama_kabupaten_kota  570 non-null    object
 6   periode_update       570 non-null    object
 7   kategori             570 non-null    object
 8   jumlah               570 non-null    int64
 9   satuan               570 non-null    object
 10  tahun                570 non-null    int64
dtypes: int64(6), object(5)
memory usage: 53.4+ KB

 Info Data Setelah Konversi ke String (selain jumlah dan tahun)
<class 'pandas.core.frame.DataFrame'>
Index: 570 entries, 3 to 2842
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   570 non-null    object
 1   id_index             570 non-null    object
 2   kode_provinsi        570 non-null    object
 3   nama_provinsi        570 non-null    object
 4   kode_kabupaten_kota  570 non-null    object
 5   nama_kabupaten_kota  570 non-null    object
 6   periode_update       570 non-null    object
 7   kategori             570 non-null    object
 8   jumlah               570 non-null    int64
 9   satuan               570 non-null    object
 10  tahun                570 non-null    int64
dtypes: int64(2), object(9)
memory usage: 53.4+ KB

In [427]:
# -------------------------
# 2. STANDARDISASI KAB/KOT
# -------------------------
df1_20182022['nama_kabupaten_kota'] = (
    df1_20182022['nama_kabupaten_kota']
    .str.upper()
    .str.strip()
)

daftar_kabkot = [
    'KABUPATEN PACITAN',
    'KABUPATEN PONOROGO',
    'KABUPATEN TRENGGALEK',
    'KABUPATEN TULUNGAGUNG',
    'KABUPATEN BLITAR',
    'KABUPATEN KEDIRI',
    'KABUPATEN MALANG',
    'KABUPATEN LUMAJANG',
    'KABUPATEN JEMBER',
    'KABUPATEN BANYUWANGI',
    'KABUPATEN BONDOWOSO',
    'KABUPATEN SITUBONDO',
    'KABUPATEN PROBOLINGGO',
    'KABUPATEN PASURUAN',
    'KABUPATEN SIDOARJO',
    'KABUPATEN MOJOKERTO',
    'KABUPATEN JOMBANG',
    'KABUPATEN NGANJUK',
    'KABUPATEN MADIUN',
    'KABUPATEN MAGETAN',
    'KABUPATEN NGAWI',
    'KABUPATEN BOJONEGORO',
    'KABUPATEN TUBAN',
    'KABUPATEN LAMONGAN',
    'KABUPATEN GRESIK',
    'KABUPATEN BANGKALAN',
    'KABUPATEN SAMPANG',
    'KABUPATEN PAMEKASAN',
    'KABUPATEN SUMENEP',
    'KOTA KEDIRI',
    'KOTA BLITAR',
    'KOTA MALANG',
    'KOTA PROBOLINGGO',
    'KOTA PASURUAN',
    'KOTA MOJOKERTO',
    'KOTA MADIUN',
    'KOTA SURABAYA',
    'KOTA BATU'
]

# -------------------------
# 3. CEK KELENGKAPAN KAB/KOT
# -------------------------
tidak_ada = [
    nama for nama in daftar_kabkot
    if nama not in df1_20182022['nama_kabupaten_kota'].values
]

print("\n2.Cek Kelengkapan Kabupaten/Kota")

if len(tidak_ada) > 0:
    print("Nama Kabupaten/kota yang tidak ada di dataset:")
    for nama in tidak_ada:
        print(nama)
else:
    print("Semua nama kabupaten/kota tersedia di dataset")

2.Cek Kelengkapan Kabupaten/Kota
Semua nama kabupaten/kota tersedia di dataset

In [428]:
# -------------------------
# 4. CEK DUPLIKAT
# -------------------------
jumlah_duplikat = df1_20182022.duplicated().sum()

print("\n3.Cek Data Duplikat")

if jumlah_duplikat > 0:
    print("Jumlah data duplikat:", jumlah_duplikat)
    df1_20182022 = df1_20182022.drop_duplicates()
    print("Berhasil dihapus")
else:
    print("Tidak ada data duplikat")

3.Cek Data Duplikat
Tidak ada data duplikat

In [429]:
# -------------------------
# 5. CEK MISSING VALUE
# -------------------------
missing_value = df1_20182022.isnull().sum()

print("\n4.Cek Missing Value")
for kolom in df1_20182022.columns:
    indeks_nan = df1_20182022[df1_20182022[kolom].isna()].index.tolist()

    if len(indeks_nan) > 0:
        print(f"{kolom}: {indeks_nan}")
        

if missing_value.sum() > 0:
    print("Jumlah missing value:", missing_value.sum())

    kolom_kategori = 'kategori'
    kolom_numerik = df1_20182022.select_dtypes(include='number').columns

    for kolom in kolom_numerik:
        if df1_20182022[kolom].isna().sum() > 0:
            df1_20182022[kolom] = df1_20182022.groupby(kolom_kategori)[kolom].transform(
                lambda x: x.fillna(x.median())
            )

    print("Berhasil ditangani sesuai kategori")

else:
    print("Tidak ada missing value")

4.Cek Missing Value
Tidak ada missing value

In [430]:
# -------------------------
# 6. CEK OUTLIER (IQR)
# -------------------------
hasil_outlier = []
kolom_numerik = df1_20182022.select_dtypes(include='number').columns

print("\n5.Cek Outlier (IQR)")

for kolom in kolom_numerik:

    Q1 = df1_20182022[kolom].quantile(0.25)
    Q3 = df1_20182022[kolom].quantile(0.75)

    IQR = Q3 - Q1

    batas_bawah = Q1 - 1.5 * IQR
    batas_atas = Q3 + 1.5 * IQR

    jumlah_outlier = df1_20182022[
        (df1_20182022[kolom] < batas_bawah) |
        (df1_20182022[kolom] > batas_atas)
    ]


    if len(jumlah_outlier) > 0:
        keterangan = "Ada outlier"
        print(f"\nVariabel: {kolom}")
        print(f'Jumlah Outlier: {len(jumlah_outlier)}')
        display(jumlah_outlier[['nama_kabupaten_kota', 'tahun', 'kategori', kolom]])
    else:
        print(f"\nVariabel: {kolom}")
        print("Tidak ada outlier")

5.Cek Outlier (IQR)

Variabel: jumlah
Jumlah Outlier: 24

     nama_kabupaten_kota  tahun                   kategori  jumlah
218   KABUPATEN SIDOARJO   2018      JUMLAH TENAGA PERAWAT    3164
477          KOTA MALANG   2018      JUMLAH TENAGA PERAWAT    2929
545        KOTA SURABAYA   2018      JUMLAH TENAGA PERAWAT    6872
671     KABUPATEN MALANG   2019      JUMLAH TENAGA PERAWAT    2661
793   KABUPATEN SIDOARJO   2019      JUMLAH TENAGA PERAWAT    2856
1036         KOTA MALANG   2019      JUMLAH TENAGA PERAWAT    3043
1115       KOTA SURABAYA   2019      JUMLAH TENAGA PERAWAT    6999
1237    KABUPATEN MALANG   2020      JUMLAH TENAGA PERAWAT    2735
1355  KABUPATEN SIDOARJO   2020      JUMLAH TENAGA PERAWAT    3028
1607         KOTA MALANG   2020      JUMLAH TENAGA PERAWAT    3316
1686       KOTA SURABAYA   2020      JUMLAH TENAGA PERAWAT    8814
1812    KABUPATEN MALANG   2021      JUMLAH TENAGA PERAWAT    2791
1930  KABUPATEN SIDOARJO   2021      JUMLAH TENAGA PERAWAT    2893
2186         KOTA MALANG   2021      JUMLAH TENAGA PERAWAT    3265
2260       KOTA SURABAYA   2021  JUMLAH TENAGA DOKTER UMUM    5299
2261       KOTA SURABAYA   2021      JUMLAH TENAGA PERAWAT    9444
2380    KABUPATEN MALANG   2022      JUMLAH TENAGA PERAWAT    3664
2401    KABUPATEN JEMBER   2022      JUMLAH TENAGA PERAWAT    2973
2500  KABUPATEN SIDOARJO   2022      JUMLAH TENAGA PERAWAT    3857
2631  KABUPATEN LAMONGAN   2022      JUMLAH TENAGA PERAWAT    2441
2647    KABUPATEN GRESIK   2022      JUMLAH TENAGA PERAWAT    2350
2751         KOTA MALANG   2022      JUMLAH TENAGA PERAWAT    3835
2829       KOTA SURABAYA   2022      JUMLAH TENAGA PERAWAT   11668
2830       KOTA SURABAYA   2022  JUMLAH TENAGA DOKTER UMUM    4185

Variabel: tahun
Tidak ada outlier

_DATA 2_

In [431]:
#===============================================================================
# DATA CLEANING 2023 - 2024
#===============================================================================

print("=========== DATA 2 CLEANING ===========")

# -------------------------
# 1. INFO DATA
# -------------------------
print("\n 1. Info Data:")
df2_20232024.info()

print("\n Info Data Setelah Konversi ke String (selain jumlah dan tahun)")
kolom_string = [
    'no'
]

df2_20232024[kolom_string] = df2_20232024[kolom_string].astype(str)
df2_20232024.info()

=========== DATA 2 CLEANING ===========

 1. Info Data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228 entries, 0 to 227
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   no              228 non-null    int64
 1   kabupaten/kota  228 non-null    object
 2   unit            228 non-null    object
 3   tahun           228 non-null    int64
 4   dokter          228 non-null    int64
 5   keperawatan     228 non-null    int64
 6   kebidanan       228 non-null    int64
dtypes: int64(5), object(2)
memory usage: 12.6+ KB

 Info Data Setelah Konversi ke String (selain jumlah dan tahun)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228 entries, 0 to 227
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   no              228 non-null    object
 1   kabupaten/kota  228 non-null    object
 2   unit            228 non-null    object
 3   tahun           228 non-null    int64
 4   dokter          228 non-null    int64
 5   keperawatan     228 non-null    int64
 6   kebidanan       228 non-null    int64
dtypes: int64(4), object(3)
memory usage: 12.6+ KB

In [432]:
# -------------------------
# 2. STANDARDISASI KAB/KOT
# -------------------------
df2_20232024 = df2_20232024[df2_20232024['tahun'].isin([2023, 2024])]
df2_20232024 = df2_20232024[
    df2_20232024['dokter'].notnull() &
    df2_20232024['keperawatan'].notnull() &
    df2_20232024['kebidanan'].notnull()
]

df2_20232024 = df2_20232024.rename(columns={
    'kabupaten/kota': 'nama_kabupaten_kota'
})

df2_20232024['nama_kabupaten_kota'] = (
    df2_20232024['nama_kabupaten_kota']
    .astype(str)
    .str.upper()
    .str.strip()
)

daftar_kabkot = [
    'KABUPATEN PACITAN',
    'KABUPATEN PONOROGO',
    'KABUPATEN TRENGGALEK',
    'KABUPATEN TULUNGAGUNG',
    'KABUPATEN BLITAR',
    'KABUPATEN KEDIRI',
    'KABUPATEN MALANG',
    'KABUPATEN LUMAJANG',
    'KABUPATEN JEMBER',
    'KABUPATEN BANYUWANGI',
    'KABUPATEN BONDOWOSO',
    'KABUPATEN SITUBONDO',
    'KABUPATEN PROBOLINGGO',
    'KABUPATEN PASURUAN',
    'KABUPATEN SIDOARJO',
    'KABUPATEN MOJOKERTO',
    'KABUPATEN JOMBANG',
    'KABUPATEN NGANJUK',
    'KABUPATEN MADIUN',
    'KABUPATEN MAGETAN',
    'KABUPATEN NGAWI',
    'KABUPATEN BOJONEGORO',
    'KABUPATEN TUBAN',
    'KABUPATEN LAMONGAN',
    'KABUPATEN GRESIK',
    'KABUPATEN BANGKALAN',
    'KABUPATEN SAMPANG',
    'KABUPATEN PAMEKASAN',
    'KABUPATEN SUMENEP',
    'KOTA KEDIRI',
    'KOTA BLITAR',
    'KOTA MALANG',
    'KOTA PROBOLINGGO',
    'KOTA PASURUAN',
    'KOTA MOJOKERTO',
    'KOTA MADIUN',
    'KOTA SURABAYA',
    'KOTA BATU'
]

# -------------------------
# 3. CEK KELENGKAPAN KAB/KOT
# -------------------------
tidak_ada = [
nama for nama in daftar_kabkot
if nama not in df2_20232024['nama_kabupaten_kota'].values
]


print("\n2.Cek Kelengkapan Kabupaten/Kota")

if len(tidak_ada) > 0:
    print("Nama Kabupaten/kota yang tidak ada di dataset:")
    for nama in tidak_ada:
        print(nama)
else:
    print("Semua nama kabupaten/kota tersedia di dataset")

2.Cek Kelengkapan Kabupaten/Kota
Semua nama kabupaten/kota tersedia di dataset

In [433]:
# -------------------------
# 4. CEK DUPLIKAT
# -------------------------
jumlah_duplikat = df2_20232024.duplicated().sum()

print("\n3.Cek Data Duplikat")

if jumlah_duplikat > 0:
    print("Jumlah data duplikat:", jumlah_duplikat)
    df2_20232024 = df2_20232024.drop_duplicates()
    print("Berhasil dihapus")
else:
    print("Tidak ada data duplikat")

3.Cek Data Duplikat
Tidak ada data duplikat

In [434]:
# -------------------------
# 5. CEK MISSING VALUE
# -------------------------
missing_value = df2_20232024.isnull().sum()

print("\n4.Cek Missing Value")
for kolom in df2_20232024.columns:
    indeks_nan = df2_20232024[df2_20232024[kolom].isna()].index.tolist()

    if len(indeks_nan) > 0:
        print(f"{kolom}: {indeks_nan}")
        

if missing_value.sum() > 0:
    print("Jumlah missing value:", missing_value.sum())

    kolom_kategori = 'kategori'
    kolom_numerik = df2_20232024.select_dtypes(include='number').columns

    for kolom in kolom_numerik:
        if df2_20232024[kolom].isna().sum() > 0:
            df2_20232024[kolom] = df2_20232024.groupby(kolom_kategori)[kolom].transform(
                lambda x: x.fillna(x.median())
            )

    print("Berhasil ditangani sesuai kategori")

else:
    print("Tidak ada missing value")

4.Cek Missing Value
Tidak ada missing value

In [435]:
# -------------------------
# 6. CEK OUTLIER (IQR)
# -------------------------
hasil_outlier = []
kolom_numerik = df2_20232024.select_dtypes(include='number').columns

print("\n5.Cek Outlier (IQR)")

for kolom in kolom_numerik:

    Q1 = df2_20232024[kolom].quantile(0.25)
    Q3 = df2_20232024[kolom].quantile(0.75)

    IQR = Q3 - Q1

    batas_bawah = Q1 - 1.5 * IQR
    batas_atas = Q3 + 1.5 * IQR

    jumlah_outlier = df2_20232024[
        (df2_20232024[kolom] < batas_bawah) |
        (df2_20232024[kolom] > batas_atas)
    ]


    if len(jumlah_outlier) > 0:
        keterangan = "Ada outlier"
        print(f"\nVariabel: {kolom}")
        print(f'Jumlah Outlier: {len(jumlah_outlier)}')
        display(jumlah_outlier[['nama_kabupaten_kota', 'unit', 'tahun', kolom]])
    else:
        print(f"\nVariabel: {kolom}")
        print("Tidak ada outlier")

5.Cek Outlier (IQR)

Variabel: tahun
Tidak ada outlier

Variabel: dokter
Jumlah Outlier: 19

,nama_kabupaten_kota,unit,tahun,dokter
36,KOTA SURABAYA,PUSKESMAS,2023,370
69,KOTA MALANG,RUMAH SAKIT,2023,393
74,KOTA SURABAYA,RUMAH SAKIT,2023,2276
82,KABUPATEN MALANG,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2023,352
85,KABUPATEN BANYUWANGI,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2023,390
90,KABUPATEN SIDOARJO,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2023,689
107,KOTA MALANG,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2023,321
112,KOTA SURABAYA,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2023,1011
150,KOTA SURABAYA,PUSKESMAS,2024,377
158,KABUPATEN MALANG,RUMAH SAKIT,2024,418
166,KABUPATEN SIDOARJO,RUMAH SAKIT,2024,328
183,KOTA MALANG,RUMAH SAKIT,2024,402
188,KOTA SURABAYA,RUMAH SAKIT,2024,2116
196,KABUPATEN MALANG,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2024,585
199,KABUPATEN BANYUWANGI,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2024,435
204,KABUPATEN SIDOARJO,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2024,799
205,KABUPATEN MOJOKERTO,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2024,343
221,KOTA MALANG,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2024,407
226,KOTA SURABAYA,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2024,1359

Variabel: keperawatan
Jumlah Outlier: 18

       nama_kabupaten_kota         unit  tahun  keperawatan
41   KABUPATEN TULUNGAGUNG  RUMAH SAKIT   2023         1476
44        KABUPATEN MALANG  RUMAH SAKIT   2023         2546
46        KABUPATEN JEMBER  RUMAH SAKIT   2023         1719
52      KABUPATEN SIDOARJO  RUMAH SAKIT   2023         3201
61      KABUPATEN LAMONGAN  RUMAH SAKIT   2023         1502
62        KABUPATEN GRESIK  RUMAH SAKIT   2023         1453
67             KOTA KEDIRI  RUMAH SAKIT   2023         1423
69             KOTA MALANG  RUMAH SAKIT   2023         3362
74           KOTA SURABAYA  RUMAH SAKIT   2023         9552
155  KABUPATEN TULUNGAGUNG  RUMAH SAKIT   2024         1518
158       KABUPATEN MALANG  RUMAH SAKIT   2024         2898
160       KABUPATEN JEMBER  RUMAH SAKIT   2024         1789
166     KABUPATEN SIDOARJO  RUMAH SAKIT   2024         3146
175     KABUPATEN LAMONGAN  RUMAH SAKIT   2024         1653
176       KABUPATEN GRESIK  RUMAH SAKIT   2024         1448
181            KOTA KEDIRI  RUMAH SAKIT   2024         1498
183            KOTA MALANG  RUMAH SAKIT   2024         3489
188          KOTA SURABAYA  RUMAH SAKIT   2024        10016

Variabel: kebidanan
Jumlah Outlier: 12

      nama_kabupaten_kota         unit  tahun  kebidanan
36          KOTA SURABAYA    PUSKESMAS   2023       1155
74          KOTA SURABAYA  RUMAH SAKIT   2023       1155
120      KABUPATEN MALANG    PUSKESMAS   2024        738
122      KABUPATEN JEMBER    PUSKESMAS   2024        983
123  KABUPATEN BANYUWANGI    PUSKESMAS   2024        723
130     KABUPATEN JOMBANG    PUSKESMAS   2024        770
135  KABUPATEN BOJONEGORO    PUSKESMAS   2024        731
137    KABUPATEN LAMONGAN    PUSKESMAS   2024        822
139   KABUPATEN BANGKALAN    PUSKESMAS   2024        912
140     KABUPATEN SAMPANG    PUSKESMAS   2024        755
142     KABUPATEN SUMENEP    PUSKESMAS   2024       1073
188         KOTA SURABAYA  RUMAH SAKIT   2024       1217

* ISI VARIABEL IDENTITAS

In [436]:
import pandas as pd

print("=========== ISI VARIABEL IDENTITAS ===========")

# ==============================================================================
# DATA MASTER VARIABEL IDENTITAS
# ==============================================================================

df_master = pd.read_csv('jumlah_tenaga_kesehatan.csv')

df_master['nama_kabupaten_kota'] = (
    df_master['nama_kabupaten_kota']
    .astype(str)
    .str.strip()
    .str.upper()
)

master_kabkot = (
    df_master[['kode_provinsi','nama_provinsi','kode_kabupaten_kota', 'nama_kabupaten_kota']]
    .drop_duplicates()
)

print("1. Data Master Variabel Identitas:")
master_kabkot

=========== ISI VARIABEL IDENTITAS ===========
1. Data Master Variabel Identitas:

     kode_provinsi nama_provinsi  kode_kabupaten_kota    nama_kabupaten_kota
0               35    JAWA TIMUR                 3501      KABUPATEN PACITAN
15              35    JAWA TIMUR                 3502     KABUPATEN PONOROGO
30              35    JAWA TIMUR                 3503   KABUPATEN TRENGGALEK
45              35    JAWA TIMUR                 3504  KABUPATEN TULUNGAGUNG
60              35    JAWA TIMUR                 3505       KABUPATEN BLITAR
75              35    JAWA TIMUR                 3506       KABUPATEN KEDIRI
90              35    JAWA TIMUR                 3507       KABUPATEN MALANG
105             35    JAWA TIMUR                 3508     KABUPATEN LUMAJANG
120             35    JAWA TIMUR                 3509       KABUPATEN JEMBER
135             35    JAWA TIMUR                 3510   KABUPATEN BANYUWANGI
150             35    JAWA TIMUR                 3511    KABUPATEN BONDOWOSO
165             35    JAWA TIMUR                 3512    KABUPATEN SITUBONDO
180             35    JAWA TIMUR                 3513  KABUPATEN PROBOLINGGO
195             35    JAWA TIMUR                 3514     KABUPATEN PASURUAN
210             35    JAWA TIMUR                 3515     KABUPATEN SIDOARJO
225             35    JAWA TIMUR                 3516    KABUPATEN MOJOKERTO
240             35    JAWA TIMUR                 3517      KABUPATEN JOMBANG
255             35    JAWA TIMUR                 3518      KABUPATEN NGANJUK
270             35    JAWA TIMUR                 3519       KABUPATEN MADIUN
285             35    JAWA TIMUR                 3520      KABUPATEN MAGETAN
300             35    JAWA TIMUR                 3521        KABUPATEN NGAWI
315             35    JAWA TIMUR                 3522   KABUPATEN BOJONEGORO
330             35    JAWA TIMUR                 3523        KABUPATEN TUBAN
345             35    JAWA TIMUR                 3524     KABUPATEN LAMONGAN
360             35    JAWA TIMUR                 3525       KABUPATEN GRESIK
375             35    JAWA TIMUR                 3526    KABUPATEN BANGKALAN
390             35    JAWA TIMUR                 3527      KABUPATEN SAMPANG
405             35    JAWA TIMUR                 3528    KABUPATEN PAMEKASAN
420             35    JAWA TIMUR                 3529      KABUPATEN SUMENEP
435             35    JAWA TIMUR                 3571            KOTA KEDIRI
450             35    JAWA TIMUR                 3572            KOTA BLITAR
465             35    JAWA TIMUR                 3573            KOTA MALANG
480             35    JAWA TIMUR                 3574       KOTA PROBOLINGGO
495             35    JAWA TIMUR                 3575          KOTA PASURUAN
510             35    JAWA TIMUR                 3576         KOTA MOJOKERTO
525             35    JAWA TIMUR                 3577            KOTA MADIUN
540             35    JAWA TIMUR                 3578          KOTA SURABAYA
555             35    JAWA TIMUR                 3579              KOTA BATU

In [437]:
# ==============================================================================
# ISI VARIABEL IDENTITAS
# ==============================================================================

df2_20232024 = df2_20232024.drop(
    columns=['kode_kabupaten_kota'],
    errors='ignore'
)

# merge
df2_20232024 = df2_20232024.merge(
    master_kabkot,
    on='nama_kabupaten_kota',
    how='left'
)

df2_20232024 = df2_20232024.sort_values(
    ['tahun', 'kode_kabupaten_kota']
).reset_index(drop=True)

df2_20232024 = df2_20232024[
    [
        'kode_provinsi',
        'nama_provinsi',
        'kode_kabupaten_kota',
        'nama_kabupaten_kota',
        'unit',
        'tahun',
        'dokter',
        'keperawatan',
        'kebidanan'
        
    ]
]


print("2. Isi Variabel Identitas pada Data 2023-2024")
df2_20232024

2. Isi Variabel Identitas pada Data 2023-2024

,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,unit,tahun,dokter,keperawatan,kebidanan
0,35,JAWA TIMUR,3501,KABUPATEN PACITAN,PUSKESMAS,2023,50,378,64
1,35,JAWA TIMUR,3501,KABUPATEN PACITAN,RUMAH SAKIT,2023,25,273,64
2,35,JAWA TIMUR,3501,KABUPATEN PACITAN,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2023,68,94,42
3,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,PUSKESMAS,2023,82,474,162
4,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,RUMAH SAKIT,2023,144,938,162
...,...,...,...,...,...,...,...,...,...
223,35,JAWA TIMUR,3578,KOTA SURABAYA,RUMAH SAKIT,2024,2116,10016,1217
224,35,JAWA TIMUR,3578,KOTA SURABAYA,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2024,1359,1120,258
225,35,JAWA TIMUR,3579,KOTA BATU,PUSKESMAS,2024,16,72,49
226,35,JAWA TIMUR,3579,KOTA BATU,RUMAH SAKIT,2024,77,497,71
227,35,JAWA TIMUR,3579,KOTA BATU,SARANA FASILITAS PELAYANAN KESEHATAN LAINNYA,2024,83,42,41

* TRANSFORMASI DATA

In [438]:
# ==============================================================================
# PIVOT JUMLAH TENAGA KESEHATAN PER KABUPATEN/KOTA PER TAHUN 2018-2022
# ==============================================================================

print("=========== TRANSFORMASI DATA ===========")

# -------------------------
# PIVOT JUMLAH TENAGA KESEHATAN
# -------------------------
df1_20182022 = df1_20182022.pivot_table(
    index=[
        'kode_provinsi',
        'nama_provinsi',
        'kode_kabupaten_kota',
        'nama_kabupaten_kota',
        'tahun'
    ],
    columns='kategori',
    values='jumlah',
    aggfunc='sum'
).reset_index()

# Rename kolom hasil pivot
df1_20182022 = df1_20182022.rename(columns={
    'JUMLAH TENAGA DOKTER UMUM': 'JUMLAH_DOKTER',
    'JUMLAH TENAGA PERAWAT': 'JUMLAH_PERAWAT',
    'JUMLAH TENAGA BIDAN': 'JUMLAH_BIDAN'
})

df1_20182022 = df1_20182022.sort_values(
    ['tahun', 'kode_kabupaten_kota'],
    ascending=[True, True]
).reset_index(drop=True)

df1_20182022

=========== TRANSFORMASI DATA ===========

kategori,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,tahun,JUMLAH_BIDAN,JUMLAH_DOKTER,JUMLAH_PERAWAT
0,35,JAWA TIMUR,3501,KABUPATEN PACITAN,2018,347,141,619
1,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2018,519,129,990
2,35,JAWA TIMUR,3503,KABUPATEN TRENGGALEK,2018,384,227,792
3,35,JAWA TIMUR,3504,KABUPATEN TULUNGAGUNG,2018,609,263,1098
4,35,JAWA TIMUR,3505,KABUPATEN BLITAR,2018,540,233,837
...,...,...,...,...,...,...,...,...
185,35,JAWA TIMUR,3575,KOTA PASURUAN,2022,237,96,485
186,35,JAWA TIMUR,3576,KOTA MOJOKERTO,2022,230,172,949
187,35,JAWA TIMUR,3577,KOTA MADIUN,2022,338,169,1337
188,35,JAWA TIMUR,3578,KOTA SURABAYA,2022,2068,4185,11668
189,35,JAWA TIMUR,3579,KOTA BATU,2022,152,154,548

In [439]:
# ==============================================================================
# AGGREGASI JUMLAH TENAGA KESEHATAN PER KABUPATEN/KOTA PER TAHUN 2023-2024
# ==============================================================================

print("=========== TRANSFORMASI DATA ===========")

# -------------------------
# PIVOT JUMLAH TENAGA KESEHATAN
# -------------------------
kolom = ['dokter', 'keperawatan', 'kebidanan']

df2_20232024 = (
    df2_20232024
    .groupby([
        'kode_provinsi',
        'nama_provinsi',
        'kode_kabupaten_kota',
        'nama_kabupaten_kota',
        'tahun'
    ])[kolom]
    .sum()
    .reset_index()
)

# Rename kolom hasil pivot
df2_20232024 = df2_20232024.rename(columns={
    'dokter': 'JUMLAH_DOKTER',
    'keperawatan': 'JUMLAH_PERAWAT',
    'kebidanan': 'JUMLAH_BIDAN'
})

df2_20232024 = df2_20232024.sort_values(
    ['tahun', 'kode_kabupaten_kota'],
    ascending=[True, True]
).reset_index(drop=True)

df2_20232024

=========== TRANSFORMASI DATA ===========

,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,tahun,JUMLAH_DOKTER,JUMLAH_PERAWAT,JUMLAH_BIDAN
0,35,JAWA TIMUR,3501,KABUPATEN PACITAN,2023,143,745,170
1,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2023,333,1646,537
2,35,JAWA TIMUR,3503,KABUPATEN TRENGGALEK,2023,182,1045,252
3,35,JAWA TIMUR,3504,KABUPATEN TULUNGAGUNG,2023,474,2394,682
4,35,JAWA TIMUR,3505,KABUPATEN BLITAR,2023,371,1278,558
...,...,...,...,...,...,...,...,...
71,35,JAWA TIMUR,3575,KOTA PASURUAN,2024,184,571,285
72,35,JAWA TIMUR,3576,KOTA MOJOKERTO,2024,203,963,251
73,35,JAWA TIMUR,3577,KOTA MADIUN,2024,310,1452,359
74,35,JAWA TIMUR,3578,KOTA SURABAYA,2024,3852,11676,2073
75,35,JAWA TIMUR,3579,KOTA BATU,2024,176,611,161

* GABUNG DATA 1 (2018-2022) DAN 2 (2023-2024)

In [440]:
# ==============================================================================
# GABUNG DATA 2018-2022 DAN 2023-2024
# ==============================================================================

print("=========== DATA GABUNGAN ===========")

df_tenagakesehatan = pd.concat([df1_20182022, df2_20232024], ignore_index=True)

df_tenagakesehatan['nama_kabupaten_kota'] = (
    df_tenagakesehatan['nama_kabupaten_kota']
    .astype(str)
    .str.upper()
    .str.strip()
)

df_tenagakesehatan_tahun_kab = df_tenagakesehatan.sort_values(
    ['tahun', 'kode_provinsi', 'nama_provinsi', 'kode_kabupaten_kota', 'nama_kabupaten_kota'],
    ascending=[True, True, True, True, True]
).reset_index(drop=True)

df_tenagakesehatan_tahun_kab

=========== DATA GABUNGAN ===========

,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,tahun,JUMLAH_BIDAN,JUMLAH_DOKTER,JUMLAH_PERAWAT
0,35,JAWA TIMUR,3501,KABUPATEN PACITAN,2018,347,141,619
1,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2018,519,129,990
2,35,JAWA TIMUR,3503,KABUPATEN TRENGGALEK,2018,384,227,792
3,35,JAWA TIMUR,3504,KABUPATEN TULUNGAGUNG,2018,609,263,1098
4,35,JAWA TIMUR,3505,KABUPATEN BLITAR,2018,540,233,837
...,...,...,...,...,...,...,...,...
261,35,JAWA TIMUR,3575,KOTA PASURUAN,2024,285,184,571
262,35,JAWA TIMUR,3576,KOTA MOJOKERTO,2024,251,203,963
263,35,JAWA TIMUR,3577,KOTA MADIUN,2024,359,310,1452
264,35,JAWA TIMUR,3578,KOTA SURABAYA,2024,2073,3852,11676
265,35,JAWA TIMUR,3579,KOTA BATU,2024,161,176,611

* SIMPAN DATA

In [441]:
#===============================================================================
# SIMPAN DATA
#===============================================================================
df_tenagakesehatan_tahun_kab.to_csv('data_jumlah_tenagakesehatan.csv', index=False)

In [442]:
print(df_tenagakesehatan_tahun_kab.columns.tolist())

['kode_provinsi', 'nama_provinsi', 'kode_kabupaten_kota', 'nama_kabupaten_kota', 'tahun', 'JUMLAH_BIDAN', 'JUMLAH_DOKTER', 'JUMLAH_PERAWAT']