# FINAL

In [1]:
import pandas as pd

# ==============================================================================
# DATA
# ==============================================================================
df_final = pd.read_csv('data_clustering_kmeans.csv')
kolom_string = [
    'kode_provinsi',
    'kode_kabupaten_kota',
]

df_final[kolom_string] = df_final[kolom_string].astype(str)

kolom_numerik = [
    col for col in df_final.select_dtypes(include='number').columns
    if col != 'tahun'
]

print("=========== DATA ===========")
df_final

=========== DATA ===========

,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,tahun,pelayanan_non_rawat_inap,pelayanan_rawat_inap,jumlah_bidan,jumlah_dokter,jumlah_perawat,jumlah_penyakit_tidak_menular,jumlah_penyakit_menular,jumlah_penduduk,cluster,sub_cluster
0,35,JAWA TIMUR,3501,KABUPATEN PACITAN,2018,9,15,347,141,619,41173,292,554394,1,1
1,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2018,12,19,519,129,990,46778,479,870705,1,1
2,35,JAWA TIMUR,3503,KABUPATEN TRENGGALEK,2018,3,19,384,227,792,40464,285,694902,1,1
3,35,JAWA TIMUR,3504,KABUPATEN TULUNGAGUNG,2018,14,18,609,263,1098,114929,507,1035290,1,1
4,35,JAWA TIMUR,3505,KABUPATEN BLITAR,2018,6,18,540,233,837,65232,392,1157500,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,35,JAWA TIMUR,3575,KOTA PASURUAN,2024,8,0,285,184,571,18844,287,219392,1,1
262,35,JAWA TIMUR,3576,KOTA MOJOKERTO,2024,6,0,251,203,963,16010,129,137393,1,1
263,35,JAWA TIMUR,3577,KOTA MADIUN,2024,6,0,359,310,1452,23764,756,201767,1,1
264,35,JAWA TIMUR,3578,KOTA SURABAYA,2024,40,23,2073,3852,11676,851331,2299,2921996,1,2
265,35,JAWA TIMUR,3579,KOTA BATU,2024,2,3,161,176,611,58862,511,222685,1,1

In [2]:
df_final['nama_kabupaten_kota'] = df_final['nama_kabupaten_kota'].str.replace(
    'KABUPATEN ', '', regex=False
)

df_final['nama_kabupaten_kota'] = (
    df_final['nama_kabupaten_kota']
    .str.replace('KOTA SURABAYA', 'SURABAYA', regex=False)
    .str.replace('KOTA BATU', 'BATU', regex=False)
)

df_final

,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,tahun,pelayanan_non_rawat_inap,pelayanan_rawat_inap,jumlah_bidan,jumlah_dokter,jumlah_perawat,jumlah_penyakit_tidak_menular,jumlah_penyakit_menular,jumlah_penduduk,cluster,sub_cluster
0,35,JAWA TIMUR,3501,PACITAN,2018,9,15,347,141,619,41173,292,554394,1,1
1,35,JAWA TIMUR,3502,PONOROGO,2018,12,19,519,129,990,46778,479,870705,1,1
2,35,JAWA TIMUR,3503,TRENGGALEK,2018,3,19,384,227,792,40464,285,694902,1,1
3,35,JAWA TIMUR,3504,TULUNGAGUNG,2018,14,18,609,263,1098,114929,507,1035290,1,1
4,35,JAWA TIMUR,3505,BLITAR,2018,6,18,540,233,837,65232,392,1157500,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,35,JAWA TIMUR,3575,KOTA PASURUAN,2024,8,0,285,184,571,18844,287,219392,1,1
262,35,JAWA TIMUR,3576,KOTA MOJOKERTO,2024,6,0,251,203,963,16010,129,137393,1,1
263,35,JAWA TIMUR,3577,KOTA MADIUN,2024,6,0,359,310,1452,23764,756,201767,1,1
264,35,JAWA TIMUR,3578,SURABAYA,2024,40,23,2073,3852,11676,851331,2299,2921996,1,2
265,35,JAWA TIMUR,3579,BATU,2024,2,3,161,176,611,58862,511,222685,1,1

In [3]:
#===============================================================================
# SIMPAN DATA
#===============================================================================
df_final.to_csv('data_clustering_final.csv', index=False)