# NORMALISASI ROBUST #

In [1]:
import pandas as pd
from sklearn.preprocessing import RobustScaler

# ==============================================================================
# DATA
# ==============================================================================
df_normalisasi = pd.read_csv('dataset_final_skripsi.csv')
kolom_string = [
    'kode_provinsi',
    'kode_kabupaten_kota',
]

df_normalisasi[kolom_string] = df_normalisasi[kolom_string].astype(str)

kolom_numerik = [
    col for col in df_normalisasi.select_dtypes(include='number').columns
    if col != 'tahun'
]

print("=========== DATA ===========")
df_normalisasi

=========== DATA ===========

,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,tahun,pelayanan_non_rawat_inap,pelayanan_rawat_inap,jumlah_bidan,jumlah_dokter,jumlah_perawat,jumlah_penyakit_tidak_menular,jumlah_penyakit_menular,jumlah_penduduk
0,35,JAWA TIMUR,3501,KABUPATEN PACITAN,2018,9,15,347,141,619,41173,292,554394
1,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2018,12,19,519,129,990,46778,479,870705
2,35,JAWA TIMUR,3503,KABUPATEN TRENGGALEK,2018,3,19,384,227,792,40464,285,694902
3,35,JAWA TIMUR,3504,KABUPATEN TULUNGAGUNG,2018,14,18,609,263,1098,114929,507,1035290
4,35,JAWA TIMUR,3505,KABUPATEN BLITAR,2018,6,18,540,233,837,65232,392,1157500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,35,JAWA TIMUR,3575,KOTA PASURUAN,2024,8,0,285,184,571,18844,287,219392
262,35,JAWA TIMUR,3576,KOTA MOJOKERTO,2024,6,0,251,203,963,16010,129,137393
263,35,JAWA TIMUR,3577,KOTA MADIUN,2024,6,0,359,310,1452,23764,756,201767
264,35,JAWA TIMUR,3578,KOTA SURABAYA,2024,40,23,2073,3852,11676,851331,2299,2921996
265,35,JAWA TIMUR,3579,KOTA BATU,2024,2,3,161,176,611,58862,511,222685

In [2]:
# ==============================================================================
# NORMALISASI ROBUST
# ==============================================================================
scaler = RobustScaler()

df_normalisasi[kolom_numerik] = scaler.fit_transform(df_normalisasi[kolom_numerik])

print("========== HASIL NORMALISASI ROBUST ==========")
df_normalisasi

========== HASIL NORMALISASI ROBUST ==========

,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,tahun,pelayanan_non_rawat_inap,pelayanan_rawat_inap,jumlah_bidan,jumlah_dokter,jumlah_perawat,jumlah_penyakit_tidak_menular,jumlah_penyakit_menular,jumlah_penduduk
0,35,JAWA TIMUR,3501,KABUPATEN PACITAN,2018,0.230769,-0.153846,-0.639716,-0.292108,-0.710573,-0.290467,-0.355131,-0.841177
1,35,JAWA TIMUR,3502,KABUPATEN PONOROGO,2018,0.461538,0.153846,-0.334074,-0.348645,-0.272298,-0.258875,-0.281465,-0.290178
2,35,JAWA TIMUR,3503,KABUPATEN TRENGGALEK,2018,-0.230769,0.153846,-0.573967,0.113074,-0.506202,-0.294463,-0.357889,-0.596418
3,35,JAWA TIMUR,3504,KABUPATEN TULUNGAGUNG,2018,0.615385,0.076923,-0.174145,0.282686,-0.144714,0.125248,-0.270435,-0.003479
4,35,JAWA TIMUR,3505,KABUPATEN BLITAR,2018,0.000000,0.076923,-0.296757,0.141343,-0.453042,-0.154862,-0.315738,0.209405
...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,35,JAWA TIMUR,3575,KOTA PASURUAN,2024,0.153846,-1.307692,-0.749889,-0.089517,-0.767277,-0.416321,-0.357101,-1.424734
262,35,JAWA TIMUR,3576,KOTA MOJOKERTO,2024,0.000000,-1.307692,-0.810307,0.000000,-0.304194,-0.432294,-0.419342,-1.567573
263,35,JAWA TIMUR,3577,KOTA MADIUN,2024,0.000000,-1.307692,-0.618392,0.504122,0.273479,-0.388590,-0.172346,-1.455436
264,35,JAWA TIMUR,3578,KOTA SURABAYA,2024,2.615385,0.461538,2.427366,17.191991,12.351447,4.275868,0.435493,3.283073
265,35,JAWA TIMUR,3579,KOTA BATU,2024,-0.307692,-1.076923,-0.970235,-0.127208,-0.720024,-0.190765,-0.268860,-1.418998

In [3]:
# =====================================================
# SIMPAN DATA
# =====================================================
df_normalisasi.to_csv(
    "dataset_final_skripsi_normalisasi.csv",
    index=False
)